In [1]:
!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

Collecting git+https://github.com/openai/whisper.git
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-05lq1mr4
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-05lq1mr4
  Resolved https://github.com/openai/whisper.git to commit c0d2f624c09dc18e709e37c2ad90c039a4eb72a2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (2.9.0+cu126)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (4.67.1)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper==20250625) (3.5.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper==20250625) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper==20250625) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper==20250625) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper==20250625) (1.11.1.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper==20250625) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper==20250625) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper==20250625) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper==20250625) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper==20250625) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper==20250625) (3.0.3)
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20250625-py3-none-any.whl size=803979 sha256=0310b4757de5c9953ba3a8a9dde137edf66821fc52d1bbb1f771cfe7963b1b93
  Stored in directory: /tmp/pip-ephem-wheel-cache-1to13r6g/wheels/c3/03/25/5e0ba78bc27a3a089f137c9f1d92fdfce16d06996c071a016c
Successfully built openai-whisper
Installing collected packages: openai-whisper
Successfully installed openai-whisper-20250625
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,961 kB]
Get:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,202 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,410 kB]
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:15 https://cli.github.com/packages stable/main amd64 Packages [345 B]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,598 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,623 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,287 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,185 kB]
Get:20 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,848 kB]
Get:21 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,532 kB]
Fetched 38.0 MB in 3s (12.1 MB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
48 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.

In [2]:
!whisper "20241128_163155-Michael-Serva.mp3" --model medium --language Spanish

100%|██████████████████████████████████████| 1.42G/1.42G [00:13<00:00, 110MiB/s]
[00:00.000 --> 00:03.000]  La 3 millones y pico de toneladas, ¿no?
[00:03.000 --> 00:06.000]  Este año es 2.8 el objetivo de toneladas.
[00:06.000 --> 00:08.000]  ¿2.8 toneladas?
[00:08.000 --> 00:12.000]  Si, el año pasado si fue 3 millones, este año ha bajado.
[00:12.000 --> 00:16.000]  Entonces tienes 1.8 entre... ¿cuánto me dices?
[00:16.000 --> 00:21.000]  2.8 millones de toneladas.
[00:21.000 --> 00:25.000]  Sale 0.64 dólares por tonelada.
[00:26.000 --> 00:31.000]  El año anterior estaba en 0.4 hasta 0.6.
[00:34.000 --> 00:39.000]  A más volumen menos costo, ¿no?
[00:42.000 --> 00:46.000]  1.8 millones de mantenimiento.
[00:48.000 --> 00:51.000]  ¿El presupuesto no lo puedes pasar?
[00:51.000 --> 00:53.000]  Si, claro.
[00:56.000 --> 01:01.000]  ¿Y vas a cumplir con todo lo planeado en el presupuesto?
[01:01.000 --> 01:05.000]  Si, hay...
[01:05.000 --> 01:08.000]  Según lo planeado si.
[01:08.000 --> 01:13.000]  Incluso nos estamos perdiendo un poco de presupuesto por actividades que no estaban planificadas.
[01:13.000 --> 01:15.000]  Que salieron por monitores de consumo.
[01:15.000 --> 01:18.000]  Bueno, por trabajo correctivo programado que aparecieron.
[01:25.000 --> 01:29.000]  ¿Y para el próximo año cuánto están... ya presentaron el presupuesto?
[01:29.000 --> 01:31.000]  1.9 millones.
[01:31.000 --> 01:32.000]  ¿El próximo año?
[01:32.000 --> 01:33.000]  Si.
[01:35.000 --> 01:40.000]  ¿Con cuánto de embarque van a tener? ¿Cuántos toneladas?
[01:40.000 --> 01:43.000]  2.9 si no me equivoco.
[01:43.000 --> 01:45.000]  ¿Millones de toneladas de embarque?
[01:45.000 --> 01:46.000]  Si.
[01:47.000 --> 01:49.000]  ¿2.9 o 1.9?
[01:49.000 --> 01:50.000]  Si.
[01:50.000 --> 01:52.000]  Lo que vendido salió.
[01:55.000 --> 01:59.000]  1.9 entre 1.9, ¿no?
[01:59.000 --> 02:06.000]  Estoy mal, es 1.52 dólares por tonelada, ¿no?
[02:07.000 --> 02:10.000]  Entonces el otro es...
[02:10.000 --> 02:14.000]  Así es, ¿no? 1.52 dólares por tonelada.
[02:14.000 --> 02:15.000]  Claro.
[02:15.000 --> 02:16.000]  Más o menos.
[02:16.000 --> 02:19.000]  El presupuesto sobre el presupuesto de embarque.
[02:20.000 --> 02:24.000]  En los próximos 5 años ¿tienes un plan de capex?
[02:24.000 --> 02:25.000]  Plan de inversiones.
[02:25.000 --> 02:29.000]  Si, para el reemplazo del mayor equipo, overhaul, etc.
[02:29.000 --> 02:33.000]  Se tiene hasta el 2030.
[02:36.000 --> 02:38.000]  Eso también necesitamos mirarlo.
[02:38.000 --> 02:39.000]  Si.
[02:39.000 --> 02:42.000]  ¿Qué es lo que tienen pronosticado?
[02:42.000 --> 02:44.000]  La faja creo que todavía está nueva, ¿no?
[02:44.000 --> 02:46.000]  Se va a cambiar en el 2027.
[02:46.000 --> 02:47.000]  ¿El 27?
[02:47.000 --> 02:50.000]  Es la de mayor logito, ¿no?
[02:50.000 --> 02:55.000]  ¿Cuántas vidas tiene esa faja tubular?
[02:55.000 --> 02:57.000]  Cinco años.
[02:57.000 --> 02:58.000]  ¿Tan poquito?
[02:58.000 --> 03:00.000]  Y está afectada en siete años.
[03:00.000 --> 03:02.000]  La primera faja que cambiamos, cinco años.
[03:02.000 --> 03:05.000]  ¿Cuántas vidas tiene esa faja tubular?
[03:05.000 --> 03:07.000]  Cinco años.
[03:07.000 --> 03:08.000]  ¿Tan poquito?
[03:08.000 --> 03:10.000]  Y está afectada en siete años.
[03:10.000 --> 03:12.000]  La primera faja que cambiamos, cinco años.
[03:12.000 --> 03:15.000]  La segunda que está actualmente funcionando, siete años.
[03:15.000 --> 03:17.000]  Se afecta a siete años.
[03:17.000 --> 03:18.000]  Por eso el 2027.
[03:18.000 --> 03:20.000]  Los últimos cambios se terminan en 2020.
[03:20.000 --> 03:22.000]  Eso también es importante.
[03:22.000 --> 03:26.000]  O sea, en este momento la faja más grande es la tubular, ¿no?
[03:28.000 --> 03:31.000]  ¿Y puede llevar hasta qué tonelaje? ¿2000?
[03:31.000 --> 03:33.000]  2200 toneladas por hora.
[03:33.000 --> 03:36.000]  2200 toneladas por hora.
[03:36.000 --> 03:39.000]  ¿Y el promedio que están usando?
[03:40.000 --> 03:41.000]  ¿1600?
[03:41.000 --> 03:43.000]  No, 2000.
[03:43.000 --> 03:45.000]  El promedio es 2000.
[03:45.000 --> 03:47.000]  El mínimo es 2650.
[03:47.000 --> 03:50.000]  ¿2000 toneladas es lo que están pasando en promedio?
[03:50.000 --> 03:52.000]  Sí, promedio.
[03:58.000 --> 04:02.000]  ¿Eso es lo que pasa en promedio al año?
[04:02.000 --> 04:04.000]  Pero no es en rate.
[04:04.000 --> 04:08.000]  No es promedio en el periodo que descargan, sino en el promedio anual.
[04:12.000 --> 04:14.000]  Estamos hablando del reto de total de...
[04:14.000 --> 04:18.000]  El promedio para tener una idea del desgaste, ¿no?
[04:18.000 --> 04:19.000]  2000.
[04:19.000 --> 04:24.000]  Porque la faja está para 2200 toneladas hora permanente, ¿no?
[04:24.000 --> 04:27.000]  Sí, 2000 toneladas está el promedio.
[04:27.000 --> 04:29.000]  ¿2000 toneladas promedio anual?
[04:29.000 --> 04:31.000]  Anual, exactamente.
[04:32.000 --> 04:36.000]  Eso es un control de productividad por parte de operaciones.
[04:36.000 --> 04:38.000]  Ya, pero...
[04:38.000 --> 04:40.000]  Lo mínimo que pueden hacer es 1600, ¿no?
[04:40.000 --> 04:42.000]  Sí, por contrato.
[04:44.000 --> 04:48.000]  Y tú podrías hacer una nota de cuánto gastas...
[04:48.000 --> 04:51.000]  Los últimos cinco años, ¿cuánto sirve el promedio?
[04:51.000 --> 04:52.000]  El costo...
[04:52.000 --> 04:57.000]  No, el promedio del aje pasado, ¿no?
[04:57.000 --> 05:01.000]  Bueno, se puede hacer entre los dos millones o el millón, ¿no?
[05:01.000 --> 05:02.000]  Sí.
[05:02.000 --> 05:06.000]  O sea, ¿cuántos tienes que hacer? ¿Cuántos tienes que pasar? ¿Dos millones? ¿Cuántos hay?
[05:06.000 --> 05:11.000]  2.8 millones. Este año, años anteriores, está en 3 millones.
[05:22.000 --> 05:26.000]  Esa faja estaría... El diseño de la faja...
[05:26.000 --> 05:28.000]  Hay que ver si...
[05:28.000 --> 05:32.000]  En realidad esa faja está sobrada para lo que están haciendo, ¿no?
[05:32.000 --> 05:35.000]  Porque trabajan períodos cortos nada más.
[05:35.000 --> 05:40.000]  No están pasando ni siquiera los 3 millones y pico que necesitan.
[05:40.000 --> 05:44.000]  Entonces no debería ser cinco añitos, sino mucho más, ¿no?
[05:44.000 --> 05:51.000]  Sí, está, si no me equivoco, por fábrica indicaron que 10 años, ¿no?
[05:51.000 --> 05:56.000]  Trabajando al régimen a 24 horas, ¿no?
[05:56.000 --> 05:57.000]  Sí.
[05:57.000 --> 05:59.000]  ¿Y eso no ocurre?
[05:59.000 --> 06:02.000]  No. En operación...
[06:02.000 --> 06:05.000]  ¿Y el espesor lo van chequeando?
[06:05.000 --> 06:12.000]  Sí, le hacemos monitoreo de ultrasonido, fijándose en el tema del desgaste.
[06:12.000 --> 06:16.000]  ¿Y cómo va el desgaste? ¿Ya han hecho su curvita?
[06:16.000 --> 06:20.000]  Sí, tenemos una tendencia de desgaste.
[06:20.000 --> 06:27.000]  Estamos cambiando los primeros tramos de la faja que se han cambiado en 2019.
[06:27.000 --> 06:32.000]  Todo el resto de la faja que se tiene está en seguimiento,
[06:32.000 --> 06:37.000]  actualmente de daños en embalmes y cantos.
[06:37.000 --> 06:45.000]  En el desgaste no hay autoridad o criticidad de la zona de retorno.
[06:45.000 --> 06:54.000]  Pero sí, se está evaluando el cambio de los espesores en la faja cantora.
[06:54.000 --> 06:59.000]  La faja tubular es la parte más importante, aparte del chill loader, ¿no?
[06:59.000 --> 07:00.000]  Sí.
[07:00.000 --> 07:02.000]  Es lo más importante, ¿no?
[07:02.000 --> 07:03.000]  Sí.
[07:03.000 --> 07:05.000]  Y lo más caro también.
[07:06.000 --> 07:08.000]  ¿Cuándo han cambiado la faja?
[07:08.000 --> 07:10.000]  En 2019.
[07:10.000 --> 07:11.000]  ¿Toda la faja?
[07:11.000 --> 07:13.000]  Sí, toda la faja.
[07:13.000 --> 07:15.000]  ¿Rabu no estaba acá, no?
[07:15.000 --> 07:17.000]  No, no está.
[07:17.000 --> 07:19.000]  ¿Quién lo hizo?
[07:19.000 --> 07:21.000]  Jinka Cereza, el otro superínquilista.
[07:21.000 --> 07:23.000]  ¿Y qué es de Jinka Cereza?
[07:23.000 --> 07:25.000]  La consultoría está ahí.
[07:25.000 --> 07:26.000]  ¿Dónde está él?
[07:26.000 --> 07:27.000]  Está en Ica.
[07:27.000 --> 07:28.000]  ¿En Ica?
[07:28.000 --> 07:30.000]  Sí, ahí vive él.
[07:30.000 --> 07:31.000]  ¿Y qué hace?
[07:31.000 --> 07:37.000]  Hace consultorías, una empresa que ha formado conocidos.
[07:37.000 --> 07:39.000]  ¿Construyó de qué mantenimiento?
[07:39.000 --> 07:41.000]  Sí, en planta.
[07:41.000 --> 07:43.000]  ¿De planta?
[07:43.000 --> 07:45.000]  Sí, tipos de planta.
[07:45.000 --> 07:49.000]  ¿Él no es el que está recomendando José Redondo?
[07:49.000 --> 07:51.000]  ¿Y en Cáceres?
[07:51.000 --> 07:53.000]  Creo que sí.
[07:53.000 --> 07:55.000]  ¿Él estuvo en Brocán?
[07:55.000 --> 07:57.000]  Sí, estuvo en Brocán.
[07:57.000 --> 07:59.000]  Estuvo en Brocán, ¿no?
[07:59.000 --> 08:01.000]  Sí, sí.
[08:03.000 --> 08:05.000]  ¿Y después también creo que en Chinaco?
[08:05.000 --> 08:07.000]  En Chinaco no, en Cerro Verde.
[08:07.000 --> 08:09.000]  Estuvo antes en Cerro Verde.
[08:09.000 --> 08:11.000]  ¿Vino acá?
[08:11.000 --> 08:13.000]  No, vino a Brocán y luego acá, o primero acá y luego a Brocán.
[08:13.000 --> 08:15.000]  Estuvo en Fochil también, en Minerares.
[08:15.000 --> 08:17.000]  Ya, ya, ya.
[08:17.000 --> 08:19.000]  En Brocán también.
[08:19.000 --> 08:21.000]  Sí, pues él es.
[08:21.000 --> 08:23.000]  Y él es el que ha...
[08:23.000 --> 08:27.000]  Cuando viene con Eduardo Kuh, ya estaba Raúl.
[08:27.000 --> 08:29.000]  Sí, por 2022.
[08:29.000 --> 08:31.000]  Sí.
[08:33.000 --> 08:35.000]  Y en Cáceres salió antes, ¿no?
[08:35.000 --> 08:37.000]  Él es el que salió.
[08:37.000 --> 08:39.000]  Y Raúl lo reemplazó.
[08:39.000 --> 08:41.000]  Sí.
[08:43.000 --> 08:45.000]  ¿Pero él era el de transportador a Callao?
[08:45.000 --> 08:47.000]  Sí, el de transportador.
[08:51.000 --> 08:53.000]  Eso se hizo en el año 2019.
[08:53.000 --> 08:55.000]  ¿Quién reemplazó esa faja?
[08:55.000 --> 08:57.000]  Fue empresa.
[08:57.000 --> 08:59.000]  Tecnomina.
[08:59.000 --> 09:01.000]  ¿Estabas acá?
[09:01.000 --> 09:03.000]  Sí.
[09:03.000 --> 09:05.000]  ¿Y cuánto tiempo duró esa faja?
[09:05.000 --> 09:07.000]  Cinco años.
[09:09.000 --> 09:11.000]  ¿Y hubo desgaste suficiente para cambiarlo?
[09:11.000 --> 09:13.000]  Sí, hubo desgaste.
[09:13.000 --> 09:17.000]  Este daño longitudinal de la faja.
[09:17.000 --> 09:19.000]  Con rotura.
[09:21.000 --> 09:23.000]  Ah, se rompió.
[09:23.000 --> 09:25.000]  Con rotura.
[09:27.000 --> 09:29.000]  ¿Y cuánto tiempo lo cambiaron?
[09:29.000 --> 09:31.000]  Se hizo progresivo.
[09:31.000 --> 09:33.000]  Ah, se fue hecho en etapas.
[09:33.000 --> 09:35.000]  Por tragos.
[09:39.000 --> 09:41.000]  2019 tiene cinco años ahorita.
[09:41.000 --> 09:43.000]  Sí.
[09:43.000 --> 09:45.000]  ¿Y cómo está la faja?
[09:45.000 --> 09:47.000]  Está en buenas condiciones.
[09:47.000 --> 09:49.000]  Hemos hecho injertos.
[09:49.000 --> 09:51.000]  Por eso se está estimando
[09:51.000 --> 09:53.000]  en el año 2020.
[09:53.000 --> 09:55.000]  Para darle una extensión de vida
[09:55.000 --> 09:57.000]  útil
[09:57.000 --> 09:59.000]  a la definición que se tiene.
[10:03.000 --> 10:05.000]  Hemos hecho algunas mejoras
[10:05.000 --> 10:07.000]  en esta última faja que se ha colocado.
[10:07.000 --> 10:09.000]  Incrementó el espesor en los cantos
[10:09.000 --> 10:11.000]  donde se veía más.
[10:11.000 --> 10:13.000]  Eso se hizo con Jim Cáceres.
[10:13.000 --> 10:15.000]  Incrementó el espesor.
[10:21.000 --> 10:23.000]  Ok.
[10:27.000 --> 10:29.000]  Hemos visto que teníamos desde el contrato
[10:29.000 --> 10:31.000]  una lista de actividades para conservación.
[10:33.000 --> 10:35.000]  ¿Cómo se han ido mejorando?
[10:35.000 --> 10:37.000]  ¿Cómo se procede mejor a esas actividades?
[10:37.000 --> 10:39.000]  ¿Cómo se ve que de repente esto no es la frecuencia?
[10:39.000 --> 10:41.000]  ¿O hay que hacer más cosas?
[10:41.000 --> 10:43.000]  ¿O estas cosas ya no hay que hacerlas?
[10:43.000 --> 10:45.000]  Sí.
[10:45.000 --> 10:47.000]  En el contrato no se menciona mantenimiento correctivo.
[10:47.000 --> 10:49.000]  No he visto solamente correntido.
[10:49.000 --> 10:51.000]  Hay que mejorar lo que hacemos tanto
[10:51.000 --> 10:53.000]  a nivel de mantenimiento preventivo
[10:53.000 --> 10:55.000]  y el tiempo exacto
[10:55.000 --> 10:57.000]  para hacer el correctivo es
[10:57.000 --> 10:59.000]  en base a los monitores de condición
[10:59.000 --> 11:01.000]  que están realizándose
[11:01.000 --> 11:03.000]  tanto con la contrata que tenemos como SKF.
[11:03.000 --> 11:05.000]  ¿Quién supervisa SKF?
[11:05.000 --> 11:07.000]  Perdona, Tramarsa.
[11:07.000 --> 11:09.000]  Tramarsa.
[11:09.000 --> 11:11.000]  ¿El contrato está bajo la supervisión de Tramarsa?
[11:11.000 --> 11:13.000]  Sí.
[11:13.000 --> 11:15.000]  Entonces eso es lo que hace
[11:15.000 --> 11:17.000]  con un punto de mejora.
[11:17.000 --> 11:19.000]  ¿Y por qué no lo hacen ustedes?
[11:19.000 --> 11:21.000]  O sea,
[11:21.000 --> 11:23.000]  ¿no tienen esas capacidades
[11:23.000 --> 11:25.000]  en esas competencias?
[11:25.000 --> 11:27.000]  Sí.
[11:27.000 --> 11:29.000]  Se propuso hacerlo con nosotros
[11:29.000 --> 11:31.000]  pero como un tema de
[11:31.000 --> 11:33.000]  enojado y experiencia
[11:33.000 --> 11:35.000]  en el mercado
[11:35.000 --> 11:37.000]  se tomó la decisión de hacerlo con
[11:37.000 --> 11:39.000]  una empresa que ya reconocieron,
[11:39.000 --> 11:41.000]  SKF,
[11:41.000 --> 11:43.000]  SoulTrack,
[11:43.000 --> 11:45.000]  que estuvieron dentro de la terna.
[11:45.000 --> 11:47.000]  Y quedaron con SKF.
[11:47.000 --> 11:49.000]  Y nos quedamos con SKF
[11:49.000 --> 11:51.000]  con otro contrato interesante.
[11:51.000 --> 11:53.000]  ¿Ellos vienen permanente acá gente?
[11:53.000 --> 11:55.000]  Permanente.
[11:55.000 --> 11:57.000]  Tres veces a la semana,
[11:57.000 --> 11:59.000]  tres días a la semana.
[11:59.000 --> 12:01.000]  ¿Vienen acá tres días a la semana?
[12:01.000 --> 12:03.000]  De ejecución en campo
[12:03.000 --> 12:05.000]  y dos días en ejecución de gabinete.
[12:05.000 --> 12:07.000]  Dos en campo,
[12:07.000 --> 12:09.000]  uno en gabinete.
[12:09.000 --> 12:11.000]  ¿Y qué cosas
[12:11.000 --> 12:13.000]  les entregan?
[12:13.000 --> 12:15.000]  Les menciona cuál es
[12:15.000 --> 12:17.000]  la condición de cada equipo.
[12:17.000 --> 12:19.000]  ¿Tienen puntos específicos
[12:19.000 --> 12:21.000]  que tomen?
[12:21.000 --> 12:23.000]  Sí, tenemos una lista completa de todos los equipos que tienen intervenir
[12:23.000 --> 12:25.000]  y los puntos de edición que tienen que tomar
[12:25.000 --> 12:27.000]  de cada equipo.
[12:27.000 --> 12:29.000]  Iluminación radial, axial.
[12:29.000 --> 12:31.000]  Iluminación, ultrasonido,
[12:31.000 --> 12:33.000]  tecografía.
[12:33.000 --> 12:35.000]  ¿Todo lo que es predictivo lo tienen ellos?
[12:35.000 --> 12:37.000]  Sí, para la parte eléctrica.
[12:37.000 --> 12:39.000]  Y si hay algún requerimiento
[12:39.000 --> 12:41.000]  adicional que se tenga
[12:41.000 --> 12:43.000]  que realizar que no esté dentro del contrato
[12:43.000 --> 12:45.000]  punto
[12:45.000 --> 12:47.000]  hacia ese spot nada más
[12:47.000 --> 12:49.000]  y solicita también.
[12:49.000 --> 12:51.000]  Ya, pero el contrato es
[12:51.000 --> 12:53.000]  ¿cuántas personas son?
[12:53.000 --> 12:55.000]  Tres. Tres personas.
[12:55.000 --> 12:57.000]  ¿Y esa persona
[12:57.000 --> 12:59.000]  siempre ha enojado de todos
[12:59.000 --> 13:01.000]  los contratos eléctricos, mecánicos
[13:01.000 --> 13:03.000]  y todo eso?
[13:03.000 --> 13:05.000]  Nosotros trabajamos en conjunto toda la información
[13:05.000 --> 13:07.000]  que ellos requieran para poder
[13:07.000 --> 13:09.000]  crear un proyecto múltiplo en despacito.
[13:09.000 --> 13:11.000]  No.
[13:11.000 --> 13:13.000]  Ok.
[13:13.000 --> 13:15.000]  ¿Es la única compañía permanente
[13:15.000 --> 13:17.000]  que está acá? ¿Es SCKF?
[13:17.000 --> 13:19.000]  No. Tenemos
[13:19.000 --> 13:21.000]  dos empresas más. ¿Quiénes son?
[13:21.000 --> 13:23.000]  Que están viendo la infraestructura, que es
[13:23.000 --> 13:25.000]  Parsa. Infraestructura.
[13:25.000 --> 13:27.000]  Infraestructura Parsa y
[13:27.000 --> 13:29.000]  Target One.
[13:29.000 --> 13:31.000]  ¿Parsa y quiénes?
[13:31.000 --> 13:33.000]  Target. Target One.
[13:33.000 --> 13:35.000]  Target. De objetivos.
[13:35.000 --> 13:37.000]  De objetivos.
[13:37.000 --> 13:39.000]  Target One.
[13:39.000 --> 13:41.000]  ¿Qué hace Parsa?
[13:41.000 --> 13:43.000]  Parsa hace renovaciones
[13:43.000 --> 13:45.000]  de
[13:45.000 --> 13:47.000]  estructuras metálicas
[13:47.000 --> 13:49.000]  hablando de barandas,
[13:49.000 --> 13:51.000]  planchas,
[13:51.000 --> 13:53.000]  diferentes niveles,
[13:53.000 --> 13:55.000]  escaleras.
[13:55.000 --> 13:57.000]  ¿Eso es más
[13:57.000 --> 13:59.000]  soldadura?
[13:59.000 --> 14:01.000]  Sí, soldadura
[14:01.000 --> 14:03.000]  y pintado también.
[14:03.000 --> 14:05.000]  ¿También pintan? Sí, pintado.
[14:05.000 --> 14:07.000]  ¿Para qué?
[14:07.000 --> 14:09.000]  Por la corrupción.
[14:09.000 --> 14:11.000]  ¿Y Target One?
[14:11.000 --> 14:13.000]  Target One es la limpieza de zonas inaccesibles.
[14:15.000 --> 14:17.000]  Zonas inaccesibles.
[14:17.000 --> 14:19.000]  Pero si no son inaccesibles, ¿cómo lo pueden limpiar?
[14:19.000 --> 14:21.000]  De difícil
[14:21.000 --> 14:23.000]  acceso será.
[14:23.000 --> 14:25.000]  Bueno,
[14:25.000 --> 14:27.000]  de los que
[14:27.000 --> 14:29.000]  están en acturas superiores
[14:29.000 --> 14:31.000]  para colgarse.
[14:31.000 --> 14:33.000]  Para colgarse.
[14:33.000 --> 14:35.000]  Para pintar.
[14:35.000 --> 14:37.000]  ¿Pintan también? Sí.
[14:37.000 --> 14:39.000]  Lo que es la misma estructura,
[14:39.000 --> 14:41.000]  las coberturas, las galerías estas.
[14:41.000 --> 14:43.000]  Eso es lo que hacemos.
[14:43.000 --> 14:45.000]  Y hoy también estamos toda la semana.
[14:45.000 --> 14:47.000]  ¿Pero son nuevos?
[14:47.000 --> 14:49.000]  Sí. Tienen
[14:49.000 --> 14:51.000]  más o menos seis meses.
[14:51.000 --> 14:53.000]  ¿Quién tiene seis meses? Target One.
[14:53.000 --> 14:55.000]  Seis meses, seis meses.
[14:55.000 --> 14:57.000]  El servicio se solicitó instantáneamente.
[14:57.000 --> 14:59.000]  ¿Cómo?
[14:59.000 --> 15:01.000]  El servicio se pidió en el mismo momento.
[15:01.000 --> 15:03.000]  El servicio fue en el mes de marzo
[15:03.000 --> 15:05.000]  más o menos.
[15:05.000 --> 15:07.000]  Para ambos requerimientos.
[15:07.000 --> 15:09.000]  Vaya. ¿No había ese servicio?
[15:09.000 --> 15:11.000]  No, no.
[15:11.000 --> 15:13.000]  Era puntual, ¿no?
[15:13.000 --> 15:15.000]  Sacábamos servicios.
[15:15.000 --> 15:17.000]  Esto ya es continuo. Eso es un contrato
[15:17.000 --> 15:19.000]  de un año. Un año. Ajá.
[15:19.000 --> 15:21.000]  ¿Cuánta gente tiene Parza?
[15:21.000 --> 15:23.000]  Cinco. Cada uno.
[15:23.000 --> 15:25.000]  Cinco, cada uno y...
[15:25.000 --> 15:27.000]  Cada empresa. ¿Ah?
[15:27.000 --> 15:29.000]  Cada empresa tiene cinco.
[15:29.000 --> 15:31.000]  Cada empresa tiene cinco personas.
[15:31.000 --> 15:33.000]  Ah, cinco personas. Pero tienen facilidades.
[15:33.000 --> 15:35.000]  Tienen camionetas, materiales, todo lo que...
[15:35.000 --> 15:37.000]  Los materiales lo probamos.
[15:37.000 --> 15:39.000]  Lo probé. Traportó a la calle.
[15:39.000 --> 15:41.000]  No fue requerimiento.
[15:41.000 --> 15:43.000]  La pintura...
[15:43.000 --> 15:45.000]  Todos los insumos para el mantenimiento
[15:45.000 --> 15:47.000]  lo probé. Traportó a la calle.
[15:47.000 --> 15:49.000]  Entonces, ¿qué ponen esta gente?
[15:49.000 --> 15:51.000]  ¿Solamente manual de obra? Manual de obra.
[15:53.000 --> 15:55.000]  Y equipos menores que realmente tienen

In [4]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df)

,LÍNEA_ID,ROL,TEXTO
0,L0001,I1,"La 3 millones y pico de toneladas, ¿no?"
1,L0002,I1,Este año es 2.8 el objetivo de toneladas.
2,L0003,E2,¿2.8 toneladas?
3,L0004,I1,"Si, el año pasado si fue 3 millones, este año ha bajado."
4,L0005,E1,Entonces tienes 1.8 entre... ¿cuánto me dices?
5,L0006,I1,2.8 millones de toneladas.
6,L0007,I1,Sale 0.64 dólares por tonelada.
7,L0008,I1,El año anterior estaba en 0.4 hasta 0.6.
8,L0009,E1,"A más volumen menos costo, ¿no?"
9,L0010,I1,1.8 millones de mantenimiento.
10,L0011,E1,¿El presupuesto no lo puedes pasar?
11,L0012,I1,"Si, claro."
12,L0013,E1,¿Y vas a cumplir con todo lo planeado en el presupuesto?
13,L0014,I1,"Si, hay..."
14,L0015,I1,Según lo planeado si.
15,L0016,I1,Incluso nos estamos perdiendo un poco de presupuesto por actividades que no estaban planificadas.
16,L0017,I1,Que salieron por monitores de consumo.
17,L0018,I1,"Bueno, por trabajo correctivo programado que aparecieron."
18,L0019,E1,¿Y para el próximo año cuánto están... ya presentaron el presupuesto?
19,L0020,I1,1.9 millones.
20,L0021,E2,¿El próximo año?
21,L0022,I1,Si.
22,L0023,E1,¿Con cuánto de embarque van a tener? ¿Cuántos toneladas?
23,L0024,I1,2.9 si no me equivoco.
24,L0025,E1,¿Millones de toneladas de embarque?
25,L0026,I1,Si.
26,L0027,E2,¿2.9 o 1.9?
27,L0028,I1,Si.
28,L0029,I1,Lo que vendido salió.
29,L0030,I1,"1.9 entre 1.9, ¿no?"
30,L0031,I1,"Estoy mal, es 1.52 dólares por tonelada, ¿no?"
31,L0032,E1,Entonces el otro es...
32,L0033,E1,"Así es, ¿no? 1.52 dólares por tonelada."
33,L0034,I1,Claro.
34,L0035,I1,Más o menos.
35,L0036,I1,El presupuesto sobre el presupuesto de embarque.
36,L0037,E1,En los próximos 5 años ¿tienes un plan de capex?
37,L0038,I1,Plan de inversiones.
38,L0039,I1,"Si, para el reemplazo del mayor equipo, overhaul, etc."
39,L0040,I1,Se tiene hasta el 2030.
40,L0041,I1,Eso también necesitamos mirarlo.
41,L0042,E2,Si.
42,L0043,E1,¿Qué es lo que tienen pronosticado?
43,L0044,E1,"La faja creo que todavía está nueva, ¿no?"
44,L0045,I1,Se va a cambiar en el 2027.
45,L0046,E2,¿El 27?
46,L0047,E1,"Es la de mayor logito, ¿no?"
47,L0048,E1,¿Cuántas vidas tiene esa faja tubular?
48,L0049,I1,Cinco años.
49,L0050,E2,¿Tan poquito?
50,L0051,I1,Y está afectada en siete años.
51,L0052,I1,"La primera faja que cambiamos, cinco años."
52,L0053,E1,¿Cuántas vidas tiene esa faja tubular?
53,L0054,I1,Cinco años.
54,L0055,E2,¿Tan poquito?
55,L0056,I1,Y está afectada en siete años.
56,L0057,I1,"La primera faja que cambiamos, cinco años."
57,L0058,I1,"La segunda que está actualmente funcionando, siete años."
58,L0059,I1,Se afecta a siete años.
59,L0060,I1,Por eso el 2027.
60,L0061,I1,Los últimos cambios se terminan en 2020.
61,L0062,I1,Eso también es importante.
62,L0063,E1,"O sea, en este momento la faja más grande es la tubular, ¿no?"
63,L0064,E1,¿Y puede llevar hasta qué tonelaje? ¿2000?
64,L0065,I1,2200 toneladas por hora.
65,L0066,I1,2200 toneladas por hora.
66,L0067,E1,¿Y el promedio que están usando?
67,L0068,E2,¿1600?
68,L0069,I1,"No, 2000."
69,L0070,I1,El promedio es 2000.
70,L0071,I1,El mínimo es 2650.
71,L0072,E1,¿2000 toneladas es lo que están pasando en promedio?
72,L0073,I1,"Sí, promedio."
73,L0074,E1,¿Eso es lo que pasa en promedio al año?
74,L0075,I1,Pero no es en rate.
75,L0076,I1,"No es promedio en el periodo que descargan, sino en el promedio anual."
76,L0077,I1,Estamos hablando del reto de total de...
77,L0078,E1,"El promedio para tener una idea del desgaste, ¿no?"
78,L0079,I1,2000.
79,L0080,I1,"Porque la faja está para 2200 toneladas hora permanente, ¿no?"
80,L0081,I1,"Sí, 2000 toneladas está el promedio."
81,L0082,E2,¿2000 toneladas promedio anual?
82,L0083,I1,"Anual, exactamente."
83,L0084,I1,Eso es un control de productividad por parte de operaciones.
84,L0085,E2,"Ya, pero..."
85,L0086,I1,"Lo mínimo que pueden hacer es 1600, ¿no?"
86,L0087,I1,"Sí, por contrato."
87,L0088,I1,Y tú podrías hacer una nota de cuánto gastas...
88,L0089,E1,"Los últimos cinco años, ¿cuánto sirve el promedio?"
89,L0090,I1,El costo...
90,L0091,E1,"No, el promedio del aje pasado, ¿no?"
91,L0092,I1,"Bueno, se puede hacer entre los dos millones o el millón, ¿no?"
92,L0093,E2,Sí.
93,L0094,E1,"O sea, ¿cuántos tienes que hacer? ¿Cuántos tienes que pasar? ¿Dos millones? ¿Cuántos hay?"
94,L0095,I1,"2.8 millones. Este año, años anteriores, está en 3 millones."
95,L0096,I1,Esa faja estaría... El diseño de la faja...
96,L0097,I1,Hay que ver si...
97,L0098,E1,"En realidad esa faja está sobrada para lo que están haciendo, ¿no?"
98,L0099,I1,Porque trabajan períodos cortos nada más.
99,L0100,I1,No están pasando ni siquiera los 3 millones y pico que necesitan.
100,L0101,E1,"Entonces no debería ser cinco añitos, sino mucho más, ¿no?"
101,L0102,I1,"Sí, está, si no me equivoco, por fábrica indicaron que 10 años, ¿no?"
102,L0103,I1,"Trabajando al régimen a 24 horas, ¿no?"
103,L0104,E2,Sí.
104,L0105,E1,¿Y eso no ocurre?
105,L0106,I1,No. En operación...
106,L0107,E1,¿Y el espesor lo van chequeando?
107,L0108,I1,"Sí, le hacemos monitoreo de ultrasonido, fijándose en el tema del desgaste."
108,L0109,E1,¿Y cómo va el desgaste? ¿Ya han hecho su curvita?
109,L0110,I1,"Sí, tenemos una tendencia de desgaste."
110,L0111,I1,Estamos cambiando los primeros tramos de la faja que se han cambiado en 2019.
111,L0112,I1,"Todo el resto de la faja que se tiene está en seguimiento,"
112,L0113,I1,actualmente de daños en embalmes y cantos.
113,L0114,I1,En el desgaste no hay autoridad o criticidad de la zona de retorno.
114,L0115,I1,"Pero sí, se está evaluando el cambio de los espesores en la faja cantora."
115,L0116,E1,"La faja tubular es la parte más importante, aparte del chill loader, ¿no?"
116,L0117,I1,Sí.
117,L0118,E1,"Es lo más importante, ¿no?"
118,L0119,I1,Sí.
119,L0120,I1,Y lo más caro también.
120,L0121,E1,¿Cuándo han cambiado la faja?
121,L0122,I1,En 2019.
122,L0123,E2,¿Toda la faja?
123,L0124,I1,"Sí, toda la faja."
124,L0125,E1,"¿Rabu no estaba acá, no?"
125,L0126,I1,"No, no está."
126,L0127,E2,¿Quién lo hizo?
127,L0128,I1,"Jinka Cereza, el otro superínquilista."
128,L0129,E1,¿Y qué es de Jinka Cereza?
129,L0130,I1,La consultoría está ahí.
130,L0131,E2,¿Dónde está él?
131,L0132,I1,Está en Ica.
132,L0133,E2,¿En Ica?
133,L0134,I1,"Sí, ahí vive él."
134,L0135,E2,¿Y qué hace?
135,L0136,I1,"Hace consultorías, una empresa que ha formado conocidos."
136,L0137,E2,¿Construyó de qué mantenimiento?
137,L0138,I1,"Sí, en planta."
138,L0139,E2,¿De planta?
139,L0140,I1,"Sí, tipos de planta."
140,L0141,E1,¿Él no es el que está recomendando José Redondo?
141,L0142,E1,¿Y en Cáceres?
142,L0143,I1,Creo que sí.
143,L0144,E2,¿Él estuvo en Brocán?
144,L0145,I1,"Sí, estuvo en Brocán."
145,L0146,E2,"Estuvo en Brocán, ¿no?"
146,L0147,I1,"Sí, sí."
147,L0148,E1,¿Y después también creo que en Chinaco?
148,L0149,I1,"En Chinaco no, en Cerro Verde."
149,L0150,I1,Estuvo antes en Cerro Verde.
150,L0151,E2,¿Vino acá?
151,L0152,I1,"No, vino a Brocán y luego acá, o primero acá y luego a Brocán."
152,L0153,I1,"Estuvo en Fochil también, en Minerares."
153,L0154,E2,"Ya, ya, ya."
154,L0155,I1,En Brocán también.
155,L0156,I1,"Sí, pues él es."
156,L0157,I1,Y él es el que ha...
157,L0158,I1,"Cuando viene con Eduardo Kuh, ya estaba Raúl."
158,L0159,I1,"Sí, por 2022."
159,L0160,E2,Sí.
160,L0161,E1,"Y en Cáceres salió antes, ¿no?"
161,L0162,I1,Él es el que salió.
162,L0163,I1,Y Raúl lo reemplazó.
163,L0164,E2,Sí.
164,L0165,E1,¿Pero él era el de transportador a Callao?
165,L0166,I1,"Sí, el de transportador."
166,L0167,I1,Eso se hizo en el año 2019.
167,L0168,E2,¿Quién reemplazó esa faja?
168,L0169,I1,Fue empresa.
169,L0170,I1,Tecnomina.
170,L0171,E2,¿Estabas acá?
171,L0172,I1,Sí.
172,L0173,E1,¿Y cuánto tiempo duró esa faja?
173,L0174,I1,Cinco años.
174,L0175,E1,¿Y hubo desgaste suficiente para cambiarlo?
175,L0176,I1,"Sí, hubo desgaste."
176,L0177,I1,Este daño longitudinal de la faja.
177,L0178,I1,Con rotura.
178,L0179,I1,"Ah, se rompió."
179,L0180,I1,Con rotura.
180,L0181,E1,¿Y cuánto tiempo lo cambiaron?
181,L0182,I1,Se hizo progresivo.
182,L0183,I1,"Ah, se fue hecho en etapas."
183,L0184,I1,Por tragos.
184,L0185,I1,2019 tiene cinco años ahorita.
185,L0186,E2,Sí.
186,L0187,E1,¿Y cómo está la faja?
187,L0188,I1,Está en buenas condiciones.
188,L0189,I1,Hemos hecho injertos.
189,L0190,I1,Por eso se está estimando
190,L0191,I1,en el año 2020.
191,L0192,I1,Para darle una extensión de vida
192,L0193,I1,útil
193,L0194,I1,a la definición que se tiene.
194,L0195,I1,Hemos hecho algunas mejoras
195,L0196,I1,en esta última faja que se ha colocado.
196,L0197,I1,Incrementó el espesor en los cantos
197,L0198,I1,donde se veía más.
198,L0199,I1,Eso se hizo con Jim Cáceres.
199,L0200,I1,Incrementó el espesor.
200,L0201,E2,Ok.
201,L0202,I1,Hemos visto que teníamos desde el contrato
202,L0203,I1,una lista de actividades para conservación.
203,L0204,E1,¿Cómo se han ido mejorando?
204,L0205,E1,¿Cómo se procede mejor a esas actividades?
205,L0206,E1,¿Cómo se ve que de repente esto no es la frecuencia?
206,L0207,E1,¿O hay que hacer más cosas?
207,L0208,E1,¿O estas cosas ya no hay que hacerlas?
208,L0209,I1,Sí.
209,L0210,I1,En el contrato no se menciona mantenimiento correctivo.
210,L0211,I1,No he visto solamente correntido.
211,L0212,I1,Hay que mejorar lo que hacemos tanto
212,L0213,I1,a nivel de mantenimiento preventivo
213,L0214,I1,y el tiempo exacto
214,L0215,I1,para hacer el correctivo es
215,L0216,I1,en base a los monitores de condición
216,L0217,I1,que están realizándose
217,L0218,I1,tanto con la contrata que tenemos como SKF.
218,L0219,E2,¿Quién supervisa SKF?
219,L0220,I1,"Perdona, Tramarsa."
220,L0221,I1,Tramarsa.
221,L0222,E1,¿El contrato está bajo la supervisión de Tramarsa?
222,L0223,I1,Sí.
223,L0224,E1,Entonces eso es lo que hace
224,L0225,I1,con un punto de mejora.
225,L0226,E1,¿Y por qué no lo hacen ustedes?
226,L0227,I1,"O sea,"
227,L0228,E2,¿no tienen esas capacidades
228,L0229,E1,en esas competencias?
229,L0230,I1,Sí.
230,L0231,I1,Se propuso hacerlo con nosotros
231,L0232,I1,pero como un tema de
232,L0233,I1,enojado y experiencia
233,L0234,I1,en el mercado
234,L0235,I1,se tomó la decisión de hacerlo con
235,L0236,I1,"una empresa que ya reconocieron,"
236,L0237,I1,"SKF,"
237,L0238,I1,"SoulTrack,"
238,L0239,I1,que estuvieron dentro de la terna.
239,L0240,I1,Y quedaron con SKF.
240,L0241,I1,Y nos quedamos con SKF
241,L0242,I1,con otro contrato interesante.
242,L0243,E1,¿Ellos vienen permanente acá gente?
243,L0244,I1,Permanente.
244,L0245,I1,"Tres veces a la semana,"
245,L0246,I1,tres días a la semana.
246,L0247,E1,¿Vienen acá tres días a la semana?
247,L0248,I1,De ejecución en campo
248,L0249,I1,y dos días en ejecución de gabinete.
249,L0250,I1,"Dos en campo,"
250,L0251,I1,uno en gabinete.
251,L0252,E2,¿Y qué cosas
252,L0253,E2,les entregan?
253,L0254,I1,Les menciona cuál es
254,L0255,I1,la condición de cada equipo.
255,L0256,E2,¿Tienen puntos específicos
256,L0257,E2,que tomen?
257,L0258,I1,"Sí, tenemos una lista completa de todos los equipos que tienen intervenir"
258,L0259,I1,y los puntos de edición que tienen que tomar
259,L0260,I1,de cada equipo.
260,L0261,I1,"Iluminación radial, axial."
261,L0262,I1,"Iluminación, ultrasonido,"
262,L0263,I1,tecografía.
263,L0264,E1,¿Todo lo que es predictivo lo tienen ellos?
264,L0265,I1,"Sí, para la parte eléctrica."
265,L0266,I1,Y si hay algún requerimiento
266,L0267,I1,adicional que se tenga
267,L0268,I1,que realizar que no esté dentro del contrato
268,L0269,I1,punto
269,L0270,I1,hacia ese spot nada más
270,L0271,I1,y solicita también.
271,L0272,E1,"Ya, pero el contrato es"
272,L0273,E1,¿cuántas personas son?
273,L0274,I1,Tres. Tres personas.
274,L0275,E2,¿Y esa persona
275,L0276,I1,siempre ha enojado de todos
276,L0277,I1,"los contratos eléctricos, mecánicos"
277,L0278,E2,y todo eso?
278,L0279,I1,Nosotros trabajamos en conjunto toda la información
279,L0280,I1,que ellos requieran para poder
280,L0281,I1,crear un proyecto múltiplo en despacito.
281,L0282,I1,No.
282,L0283,E2,Ok.
283,L0284,E1,¿Es la única compañía permanente
284,L0285,E1,que está acá? ¿Es SCKF?
285,L0286,I1,No. Tenemos
286,L0287,E1,dos empresas más. ¿Quiénes son?
287,L0288,I1,"Que están viendo la infraestructura, que es"
288,L0289,I1,Parsa. Infraestructura.
289,L0290,I1,Infraestructura Parsa y
290,L0291,I1,Target One.
291,L0292,E2,¿Parsa y quiénes?
292,L0293,I1,Target. Target One.
293,L0294,I1,Target. De objetivos.
294,L0295,I1,De objetivos.
295,L0296,I1,Target One.
296,L0297,E2,¿Qué hace Parsa?
297,L0298,I1,Parsa hace renovaciones
298,L0299,E2,de
299,L0300,I1,estructuras metálicas
300,L0301,I1,"hablando de barandas,"
301,L0302,I1,"planchas,"
302,L0303,I1,"diferentes niveles,"
303,L0304,I1,escaleras.
304,L0305,E2,¿Eso es más
305,L0306,E2,soldadura?
306,L0307,I1,"Sí, soldadura"
307,L0308,I1,y pintado también.
308,L0309,E2,"¿También pintan? Sí, pintado."
309,L0310,E2,¿Para qué?
310,L0311,I1,Por la corrupción.
311,L0312,E2,¿Y Target One?
312,L0313,I1,Target One es la limpieza de zonas inaccesibles.
313,L0314,I1,Zonas inaccesibles.
314,L0315,E1,"Pero si no son inaccesibles, ¿cómo lo pueden limpiar?"
315,L0316,I1,De difícil
316,L0317,I1,acceso será.
317,L0318,E2,"Bueno,"
318,L0319,I1,de los que
319,L0320,I1,están en acturas superiores
320,L0321,I1,para colgarse.
321,L0322,I1,Para colgarse.
322,L0323,I1,Para pintar.
323,L0324,E2,¿Pintan también? Sí.
324,L0325,I1,"Lo que es la misma estructura,"
325,L0326,I1,"las coberturas, las galerías estas."
326,L0327,I1,Eso es lo que hacemos.
327,L0328,I1,Y hoy también estamos toda la semana.
328,L0329,E2,¿Pero son nuevos?
329,L0330,I1,Sí. Tienen
330,L0331,I1,más o menos seis meses.
331,L0332,E1,¿Quién tiene seis meses? Target One.
332,L0333,I1,"Seis meses, seis meses."
333,L0334,I1,El servicio se solicitó instantáneamente.
334,L0335,E2,¿Cómo?
335,L0336,I1,El servicio se pidió en el mismo momento.
336,L0337,I1,El servicio fue en el mes de marzo
337,L0338,I1,más o menos.
338,L0339,I1,Para ambos requerimientos.
339,L0340,E1,Vaya. ¿No había ese servicio?
340,L0341,I1,"No, no."
341,L0342,E2,"Era puntual, ¿no?"
342,L0343,I1,Sacábamos servicios.
343,L0344,I1,Esto ya es continuo. Eso es un contrato
344,L0345,I1,de un año. Un año. Ajá.
345,L0346,E2,¿Cuánta gente tiene Parza?
346,L0347,I1,Cinco. Cada uno.
347,L0348,I1,"Cinco, cada uno y..."
348,L0349,E2,Cada empresa. ¿Ah?
349,L0350,I1,Cada empresa tiene cinco.
350,L0351,I1,Cada empresa tiene cinco personas.
351,L0352,I1,"Ah, cinco personas. Pero tienen facilidades."
352,L0353,I1,"Tienen camionetas, materiales, todo lo que..."
353,L0354,I1,Los materiales lo probamos.
354,L0355,I1,Lo probé. Traportó a la calle.
355,L0356,I1,No fue requerimiento.
356,L0357,I1,La pintura...
357,L0358,I1,Todos los insumos para el mantenimiento
358,L0359,I1,lo probé. Traportó a la calle.
359,L0360,E1,"Entonces, ¿qué ponen esta gente?"
360,L0361,E1,¿Solamente manual de obra? Manual de obra.
361,L0362,I1,Y equipos menores que realmente tienen
362,L0363,I1,para el control de calidad de sus
363,L0364,I1,actividades.
364,L0365,I1,"Y los andaámeos, los..."
365,L0366,I1,Va con parte de sus servicios.
366,L0367,I1,"O sea, los insumos, sí,"
367,L0368,I1,vienen por la transportadora y
368,L0369,I1,el resto viene por ellos.
369,L0370,I1,Equipos especiales como Manleaf.
370,L0371,I1,Manleaf de ellos también.
371,L0372,I1,"Ah, transportadora."
372,L0373,E1,¿Y quién los supervisa? ¿Ustedes?
373,L0374,I1,"Sí. O sea, transportadora que allá"
374,L0375,I1,uno los contrata y usted el tramasa
375,L0376,I1,los supervisa. Sí.
376,L0377,E2,Ok.
377,L0378,E1,"Tríos, ¿de dónde?"
378,L0379,I1,Sobre la criticidad
379,L0380,E1,"de los equipos, ¿no? Que tienen una"
380,L0381,I1,forma de calcularlos en contra de los equipos.
381,L0382,I1,Eso se...
382,L0383,I1,Se está revisando en el tiempo
383,L0384,I1,para ver si un equipo
384,L0385,I1,por alguna razón se vuelve más crítico
385,L0386,I1,o ha cambiado
386,L0387,I1,de repente la forma de terminar
387,L0388,I1,cuando un equipo es crítico. Inicialmente
388,L0389,I1,nosotros como Tramarsas teníamos esa
389,L0390,I1,esa evaluación de análisis de criticidad
390,L0391,I1,del equipo.
391,L0392,I1,A la presenta que este año pasó
392,L0393,I1,en base a una auditoría que tuvimos de calidad
393,L0394,I1,los profesionales de la transportadora
394,L0395,I1,deberían manejar esa análisis de criticidad.
395,L0396,I1,"Pero sí, año a año"
396,L0397,I1,se va evaluando el tema
397,L0398,I1,de la criticidad en base a
398,L0399,I1,"factores como la operacionalidad,"
399,L0400,I1,"tiempo de falla de cada uno de los equipos,"
400,L0401,I1,"si afectaba o no la seguridad,"
401,L0402,I1,"si un tema de logística que se debe tener en stand-by,"
402,L0403,I1,se ha hecho una evaluación
403,L0404,I1,y actualmente ya
404,L0405,I1,la tienda es que bajo su
405,L0406,I1,estándar mantiene otra operacionalidad.
406,L0407,I1,Es parte
407,L0408,I1,de su contra incluso.
408,L0409,I1,Y a partir de ahí
409,L0410,E1,"entonces ellos, las mejores"
410,L0411,I1,o el cambio de los criterios
411,L0412,I1,está por responsabilidad de ellos.
412,L0413,I1,Ustedes lo reciben como insumo.
413,L0414,I1,"Equipo crítico, equipo crítico."
414,L0415,E1,¿Y qué niveles de criticidad hay?
415,L0416,I1,Tenemos la faja.
416,L0417,I1,"O no, digo, los niveles de criticidad."
417,L0418,I1,"Ah, estos son solo tres niveles."
418,L0419,I1,"Críticos, mediadamente críticos"
419,L0420,I1,y no críticos.
420,L0421,E2,OK.
421,L0422,E1,¿Y críticos que va a hacer?
422,L0423,I1,"No, mediadamente los equipos de la línea principal."
423,L0424,I1,"Fajas, estores."
424,L0425,E2,OK.
425,L0426,I1,El teléfono.
426,L0427,I1,En cuanto a
427,L0428,I1,el mantenimiento
428,L0429,I1,para equipos regulados
429,L0430,I1,equipos por ley
430,L0431,I1,tienen que tener un tratamiento especial.
431,L0432,E2,¿Tienen ustedes
432,L0433,E1,ese tipo de equipos?
433,L0434,E2,¿Tienen alguna
434,L0435,I1,"reglamentación especial, alguna norma"
435,L0436,I1,que te diga que tiene que ser un tipo específico
436,L0437,E1,"de mantenimiento, de control sobre el mundo de ellos?"
437,L0438,I1,Claro. Equipos como
438,L0439,I1,el sistema de trizón e incendios
439,L0440,I1,están bajo la norma y tenemos que tener
440,L0441,I1,certificaciones.
441,L0442,I1,Las pozas a tierra también están
442,L0443,I1,controladas base a la norma
443,L0444,I1,eléctrica con la ley
444,L0445,I1,de ecuadignación electricidad.
445,L0446,I1,El tema de
446,L0447,I1,las oleas.
447,L0448,I1,Tenemos a lo que requiere el fabricante
448,L0449,I1,para los que es calado de los rodamientos.
449,L0450,I1,Así como estos
450,L0451,I1,hay varios
451,L0452,I1,temas también de las reparaciones
452,L0453,I1,organizados de las fajas.
453,L0454,I1,Está establecido también su temperatura y presión
454,L0455,I1,con cual del
455,L0456,I1,de organización de la actividad
456,L0457,I1,para realizar la calidad del
457,L0458,I1,trabajo.
458,L0459,E1,¿Y eso de ahí tiene
459,L0460,E1,"registros? ¿Tiene evidencia, almacenada"
460,L0461,E2,e insistematica?
461,L0462,I1,"Sí, tenemos registro porque es controlado"
462,L0463,I1,también en las auditorías.
463,L0464,I1,Igual que la balanza
464,L0465,I1,tiene que estar calibrada y certificada
465,L0466,I1,sus pesas patrón
466,L0467,I1,que tenemos en nuestras fajas
467,L0468,I1,y todo lo más
468,L0469,I1,que mencionamos.
469,L0470,E1,¿Y allí quién es el responsable
470,L0471,E1,de generar la información?
471,L0472,I1,Nosotros
472,L0473,I1,es lo que establecemos
473,L0474,I1,todo lo que debe.
474,L0475,E1,Ya se estableció en realidad
475,L0476,I1,lo que es tener
476,L0477,I1,especificado un control
477,L0478,I1,de calidad peligrosa.
478,L0479,E2,¿Y quién se encarga?
479,L0480,E1,¿Quién tiene la base de datos
480,L0481,E1,o el repositorio?
481,L0482,I1,Se entrega.
482,L0483,I1,Nosotros lo decimos tanto como transportador
483,L0484,I1,lo que ha sido la información como trámase.
484,L0485,I1,Pero como flujo de
485,L0486,I1,aprobación y finalmente el pago
486,L0487,I1,que también va de la mano
487,L0488,I1,"lo validamos, lo enviamos"

In [3]:
!whisper "20241128_160952-Michael-Serva.mp3" --model medium --language Spanish

[00:00.000 --> 00:10.000]  Entonces, ¿en la cometida va a llegar eso de atacar a ustedes?
[00:10.000 --> 00:18.000]  Sí, para lo que es inspecciones, pero para intervenciones ya es como un producto.
[00:18.000 --> 00:22.000]  Claro, pero acá dice inspección y mantenimiento del sistema eléctrico.
[00:22.000 --> 00:24.000]  Mantenimiento no queda claro qué es cosa de mantenimiento.
[00:24.000 --> 00:27.000]  Sí, no es muy específico.
[00:27.000 --> 00:33.000]  Inspección y mantenimiento de los sistemas electrónicos.
[00:33.000 --> 00:38.000]  Igualito también hay mantenimiento, pero es mantenimiento preventivo.
[00:38.000 --> 00:43.000]  A la luz de lo que el objetivo de ustedes es prevenir, entonces es mantenimiento preventivo.
[00:43.000 --> 00:45.000]  Limpieza, ajustes...
[00:45.000 --> 00:48.000]  Ya, inspección y mantenimiento de los sistemas electrónicos.
[00:48.000 --> 00:51.000]  Inspección y mantenimiento del sistema hidráulico.
[00:51.000 --> 00:54.000]  Inspección y mantenimiento del sistema de transmisión.
[00:54.000 --> 00:58.000]  Inspección y mantenimiento preventivo de las estructuras metálicas.
[00:58.000 --> 01:01.000]  Cuida a soldadoras mientras lubricación y engrace.
[01:01.000 --> 01:04.000]  Revisión y reposición del nivel del lubricante.
[01:04.000 --> 01:07.000]  Comprobación del funcionamiento de todos los puntos de engrace.
[01:07.000 --> 01:09.000]  Cambio de parte de elementos menores.
[01:09.000 --> 01:11.000]  Reparación de menores dentro del terminal.
[01:11.000 --> 01:13.000]  Control de megado.
[01:13.000 --> 01:15.000]  Control de pozos en tierra.
[01:15.000 --> 01:17.000]  Imposición del sistema contraincendios.
[01:17.000 --> 01:19.000]  ¿Tiene sistema contraincendios?
[01:19.000 --> 01:21.000]  De detección.
[01:21.000 --> 01:23.000]  ¿Detección que te da alarma?
[01:23.000 --> 01:25.000]  Sí, tiene sensores de humo.
[01:25.000 --> 01:28.000]  ¿En la escala te vota el aviso?
[01:28.000 --> 01:29.000]  Sí.
[01:29.000 --> 01:31.000]  ¿Tienes que correr contra el extinguidor?
[01:31.000 --> 01:33.000]  Y vestigar.
[01:33.000 --> 01:35.000]  No tiene mitigación.
[01:35.000 --> 01:38.000]  ¿Cualquier otra que me haga directo, evidentemente?
[01:45.000 --> 01:48.000]  Trabajo menores, o sea trabajo preventivos.
[01:49.000 --> 01:52.000]  Y eso es sobre el terminal.
[01:52.000 --> 01:55.000]  Esta es la parte que se ve como preventivo.
[01:55.000 --> 02:00.000]  Y a continuación, lo rutinario, nuestro concepto, se me enfoca en lo que son las obras.
[02:00.000 --> 02:02.000]  Esos son los activos.
[02:02.000 --> 02:05.000]  Imposición y reporte de estado de conservación del muelle del terminal.
[02:05.000 --> 02:09.000]  Imposición y reporte de estado de conservación de las estructuras metálicas.
[02:09.000 --> 02:12.000]  Imposición y reporte de los pavimentos.
[02:12.000 --> 02:17.000]  Imposición y reporte de estado de conservación de los edificios y piscinas.
[02:17.000 --> 02:20.000]  Imposición y reporte de estado de mantenimiento.
[02:20.000 --> 02:24.000]  Imposición y reporte de estado de conservación de las redes de agua.
[02:24.000 --> 02:29.000]  Imposición y reporte de estado de conservación de las redes de los sabres.
[02:32.000 --> 02:36.000]  Iluminación, tableras de control, fuerza en baja tensión.
[02:41.000 --> 02:44.000]  Imposición y medición de profundidad operativa.
[02:44.000 --> 02:46.000]  ¿Tienen buzos?
[02:46.000 --> 02:48.000]  Tienen muy bien.
[02:50.000 --> 02:53.000]  Pero si están a cargo de eso, tienen que estar mirando.
[02:53.000 --> 02:57.000]  Sí, hemos hecho servicios de mantenimiento de kilogotes, las defensas.
[02:57.000 --> 02:59.000]  ¿Tú estás a cargo de eso también?
[02:59.000 --> 03:01.000]  Sí, o sea, supervisamos finalmente, ¿no?
[03:01.000 --> 03:02.000]  Ya.
[03:02.000 --> 03:07.000]  Todos los kilogotes, los que están en la base de la limpieza.
[03:07.000 --> 03:10.000]  ¿Tienes ahí tu...?
[03:10.000 --> 03:12.000]  O sea, ¿está a cargo de ustedes?
[03:12.000 --> 03:17.000]  Nosotros solicitamos el servicio y lo supervisamos y validamos finalmente el reporte.
[03:17.000 --> 03:19.000]  Tienen protección católica, ¿no?
[03:19.000 --> 03:20.000]  Sí.
[03:20.000 --> 03:23.000]  Hacen las mediciones de los años de sapejismo.
[03:23.000 --> 03:24.000]  Ya.
[03:27.000 --> 03:35.000]  ¿Y entonces los trabajos que nacen como consecuencia de esto, trabajos mayores, eso no está a cargo de ustedes?
[03:35.000 --> 03:36.000]  No.
[03:36.000 --> 03:43.000]  Pues justamente porque en la parte final de este contrato hay una cantidad de equipos y todas las herramientas que se necesitan.
[03:43.000 --> 03:47.000]  Bajo esa evaluación se indicaría el requerimiento mayor.
[03:49.000 --> 03:59.000]  O sea, ¿está claro que el mantenimiento correctivo programado, que escape de esto que estamos viendo acá, no está a cargo de ustedes?
[03:59.000 --> 04:00.000]  Exacto.
[04:00.000 --> 04:02.000]  ¿Y quién tiene la responsabilidad?
[04:02.000 --> 04:11.000]  Nosotros al hacer el mantenimiento menor tenemos que notificar e indicar a TC que se hace requerimiento para su evaluación.
[04:11.000 --> 04:12.000]  Hay un tema acá de claro.
[04:12.000 --> 04:13.000]  Sí.
[04:13.000 --> 04:16.000]  Entonces, se hace un término de referencia.
[04:16.000 --> 04:17.000]  ¿Quién hace el término de referencia?
[04:17.000 --> 04:18.000]  Tramarsa.
[04:18.000 --> 04:22.000]  Y hacemos las evaluaciones con firmas, ¿no?
[04:22.000 --> 04:27.000]  Pasan por cada uno de los consejos de Tramarsa y también los de transportar a calle.
[04:27.000 --> 04:28.000]  Ajá.
[04:28.000 --> 04:31.000]  Si está aprobado procedemos al ejecutado.
[04:31.000 --> 04:39.000]  Básicamente el 99% se justifica para poder ser atendido por un proveedor.
[04:39.000 --> 04:40.000]  Ya.
[04:40.000 --> 04:42.000]  ¿Y la supervisión del proveedor quién lo hace a ustedes?
[04:42.000 --> 04:43.000]  Sí.
[04:43.000 --> 04:50.000]  Como Tramarsa hacemos una supervisión durante la ejecución y también le damos el cierre al término de diálogo.
[04:50.000 --> 04:52.000]  Te reciben el informe.
[04:52.000 --> 04:54.000]  Pero eso no está ahí pero lo están haciendo.
[04:54.000 --> 04:56.000]  Sí, lo estamos haciendo.
[04:56.000 --> 04:57.000]  Ya.
[04:57.000 --> 05:05.000]  Entonces, cuando se termine la ejecución ya se le emite ese informe a la transportadora para que ellos procedan con los pagos.
[05:05.000 --> 05:06.000]  Ya.
[05:06.000 --> 05:12.000]  Entonces, ustedes identifican el trabajo, el proceso de identificación del trabajo lo hacen ustedes.
[05:12.000 --> 05:13.000]  Ajá.
[05:13.000 --> 05:18.000]  Identifican con el trabajo de bandito preventivo y los planes de mantenimiento, identifican el trabajo realizado.
[05:18.000 --> 05:19.000]  Sí.
[05:19.000 --> 05:20.000]  Sí.
[05:20.000 --> 05:21.000]  Ese es el responsable de ustedes.
[05:21.000 --> 05:22.000]  Ajá.
[05:22.000 --> 05:23.000]  Identifica el trabajo.
[05:23.000 --> 05:24.000]  Ajá.
[05:25.000 --> 05:33.000]  Y luego entra el área de mantenimiento y el mantenimiento tiene que hacer su planificación, hace sus términos de referencia,
[05:33.000 --> 05:34.000]  especifica el trabajo realizado.
[05:34.000 --> 05:35.000]  Ajá.
[05:35.000 --> 05:38.000]  Si es que no lo tienen ustedes dentro de este tipo de trabajo.
[05:38.000 --> 05:40.000]  El de ustedes es hacer los términos de referencia.
[05:40.000 --> 05:41.000]  Ajá.
[05:41.000 --> 05:44.000]  Y lo entregan para que lo liciten.
[05:44.000 --> 05:45.000]  ¿Quién?
[05:45.000 --> 05:46.000]  Transportadora Callao.
[05:46.000 --> 05:47.000]  Que lo apruebe el transportador Callao.
[05:47.000 --> 05:49.000]  Transportador Callao tiene que aprobarlo.
[05:49.000 --> 05:50.000]  Ajá.
[05:50.000 --> 05:52.000]  Y salida la licitación porque ellos tienen el proceso de procura.
[05:52.000 --> 05:53.000]  Ajá.
[05:53.000 --> 05:54.000]  Ellos hacen procura.
[05:54.000 --> 06:00.000]  Tramarza, hay un servicio que hace, que tiene Tramarza para lo que es la procura.
[06:00.000 --> 06:01.000]  O sea.
[06:01.000 --> 06:09.000]  O sea, inicia con mandívido Tramarza, se le envía al transportador, al transportador en general el requerimiento con una orden de compra del servicio material,
[06:09.000 --> 06:13.000]  se lo emite al área de adquisiciones Tramarza que tiene un contrato.
[06:13.000 --> 06:14.000]  Ajá.
[06:14.000 --> 06:15.000]  Entonces Tramarza hace la licitación.
[06:15.000 --> 06:16.000]  Sí.
[06:16.000 --> 06:19.000]  Ellos tienen el cargo de seleccionar el equipo.
[06:19.000 --> 06:20.000]  Sí.
[06:20.000 --> 06:30.000]  En el proceso de adquisiciones de procura, la parte de mantenimiento es valida en la parte técnica de la terna de proveedores.
[06:30.000 --> 06:32.000]  ¿Cómo no entiende eso?
[06:32.000 --> 06:41.000]  O sea, la participación técnica, la evaluación técnica de la terna que haya conseguido la adquisición del área de adquisiciones.
[06:41.000 --> 06:42.000]  De Tramarza.
[06:42.000 --> 06:47.000]  De Tramarza es valida por mantenimiento de Tramarza y TC.
[06:48.000 --> 06:54.000]  Y el tema de los costos es validado por transportar al área.
[06:54.000 --> 07:01.000]  La parte técnica se corresponsabiliza del transportador encallado y ustedes.
[07:01.000 --> 07:02.000]  Sí.
[07:02.000 --> 07:03.000]  Dan opinión técnica.
[07:03.000 --> 07:04.000]  Correcto.
[07:04.000 --> 07:05.000]  Pero costo decide Tramarza.
[07:05.000 --> 07:06.000]  O perdón.
[07:06.000 --> 07:07.000]  Este transportador encallado.
[07:07.000 --> 07:08.000]  Ya.
[07:08.000 --> 07:09.000]  Ok.
[07:10.000 --> 07:16.000]  ¿Ustedes cotizan algún trabajo mayor?
[07:16.000 --> 07:33.000]  Es poco, sí, pero sí hay indicaciones de transportador con la autorización de cotizar fabricaciones de poleas, fabricaciones de polines, ese tipo de materiales.
[07:33.000 --> 07:35.000]  Pero ustedes lo mandan a hacer.
[07:35.000 --> 07:37.000]  Claro, lo solicitamos.
[07:37.000 --> 07:38.000]  No, no, no.
[07:38.000 --> 07:39.000]  Me pregunto.
[07:39.000 --> 07:42.000]  ¿Ustedes compiten con los que también...
[07:42.000 --> 07:43.000]  No.
[07:43.000 --> 07:44.000]  ¿No?
[07:44.000 --> 07:45.000]  No.
[07:45.000 --> 07:46.000]  No, no hacemos eso.
[07:46.000 --> 07:47.000]  No hacemos.
[07:47.000 --> 07:49.000]  No hemos competido bajo...
[07:49.000 --> 07:52.000]  Por ejemplo, un trabajo mayor y yo también quiero hacerlo.
[07:52.000 --> 07:53.000]  ¿No hacen eso ustedes?
[07:53.000 --> 07:54.000]  No.
[07:54.000 --> 07:55.000]  ¿Por qué?
[07:55.000 --> 08:02.000]  Bajo las últimas conversiones que ya tenemos con transportador, al ser un vendedor...
[08:02.000 --> 08:04.000]  No puede ser juez y parte, dice.
[08:04.000 --> 08:06.000]  No podemos ser juez y parte.
[08:07.000 --> 08:08.000]  Ajá.
[08:08.000 --> 08:10.000]  Y todavía no se ha determinado si alguna vez...
[08:10.000 --> 08:12.000]  Pero para eso están ellos, ¿no?
[08:12.000 --> 08:13.000]  El transportador ha callado.
[08:13.000 --> 08:14.000]  Así es.
[08:14.000 --> 08:17.000]  Alguna vez se quiso regresar, pero no se ha definido si podemos participar.
[08:17.000 --> 08:21.000]  Simplemente se ha mencionado que no podemos ser juez y parte para cualquier requerimiento.
[08:21.000 --> 08:23.000]  ¿Y no sería más barato a ustedes?
[08:23.000 --> 08:25.000]  Sí, se planteó de esa manera.
[08:25.000 --> 08:27.000]  La propuesta se planteó de esa manera.
[08:27.000 --> 08:29.000]  Pero no había una respuesta...
[08:29.000 --> 08:32.000]  ¿Y ustedes tienen intenciones de hacer eso?
[08:32.000 --> 08:33.000]  ¿Quieren hacer eso?
[08:33.000 --> 08:35.000]  Ha habido intenciones en algún momento.
[08:35.000 --> 08:36.000]  ¿Ha habido?
[08:36.000 --> 08:37.000]  Sí, ha habido.
[08:37.000 --> 08:38.000]  ¿Ya no hay?
[08:39.000 --> 08:40.000]  Las últimas veces...
[08:42.000 --> 08:46.000]  ¿El nuevo gerente no tiene intenciones de ir en esa dirección?
[08:47.000 --> 08:53.000]  Ha habido, como mencionó, propuestas, pero no ha llegado a ningún punto de...
[08:53.000 --> 08:54.000]  ¿A un buen acuerdo?
[08:54.000 --> 08:55.000]  Exacto.
[08:56.000 --> 08:57.000]  Sí, incluido...
[08:57.000 --> 08:58.000]  Ya.
[08:58.000 --> 08:59.000]  Ok.
[08:59.000 --> 09:03.000]  Entonces ustedes identifican el trabajo, define lo que hay que hacer.
[09:03.000 --> 09:07.000]  Se lo pasan con términos de referencia al área de planificación.
[09:07.000 --> 09:09.000]  O el planificación es el que hace todo eso.
[09:09.000 --> 09:10.000]  Sí.
[09:10.000 --> 09:11.000]  Y luego dice a Procura, ¿sabes qué?
[09:11.000 --> 09:12.000]  Esto es lo que necesitamos.
[09:12.000 --> 09:13.000]  Correcto.
[09:13.000 --> 09:16.000]  ¿Esto lo revisa el transportador acallado antes de que salga?
[09:16.000 --> 09:18.000]  ¿O ustedes van por su lado nada más?
[09:18.000 --> 09:21.000]  No, lo revisamos en conjunto.
[09:21.000 --> 09:22.000]  Lo prueban.
[09:22.000 --> 09:24.000]  Porque siempre hay los postores finales con los...
[09:24.000 --> 09:26.000]  No, pero antes de salir a licitación.
[09:26.000 --> 09:27.000]  No, no, no.
[09:27.000 --> 09:28.000]  No me dejo entender.
[09:28.000 --> 09:31.000]  Tú estás con tu gente trabajando el mantenimiento.
[09:31.000 --> 09:38.000]  Identificas cambios en un reductor, por ejemplo, porque está vibrando, está calentando,
[09:38.000 --> 09:41.000]  está saliendo de servicio cada rato, lo que sea.
[09:41.000 --> 09:42.000]  Digo, no, no, no.
[09:42.000 --> 09:43.000]  Esto está mal.
[09:43.000 --> 09:46.000]  Vamos a tener que reemplazarlo en la manera posible.
[09:46.000 --> 09:49.000]  Entonces, o repararlo, o alinearlo.
[09:50.000 --> 09:53.000]  Ese trabajo específico pasa...
[09:53.000 --> 09:58.000]  Ustedes identificaron el trabajo y necesitan corregir esa deficiencia.
[09:58.000 --> 09:59.000]  Ajá.
[09:59.000 --> 10:04.000]  Y deciden que necesitan un tercero.
[10:04.000 --> 10:07.000]  ¿Quién hace los términos de referencia?
[10:07.000 --> 10:08.000]  Ustedes.
[10:08.000 --> 10:09.000]  Vamos.
[10:09.000 --> 10:10.000]  Ya.
[10:10.000 --> 10:14.000]  ¿Y quién pasa al departamento de compras de Tramarsa también?
[10:14.000 --> 10:18.000]  O sea, Planificación Tramarsa le manda a compras Tramarsa.
[10:18.000 --> 10:21.000]  Claro, después de las aprobaciones se le envía...
[10:21.000 --> 10:22.000]  Ya.
[10:22.000 --> 10:24.000]  Licitan y vienen tres.
[10:24.000 --> 10:28.000]  Ustedes revisan la parte técnica conjuntamente con tres licitaciones.
[10:28.000 --> 10:29.000]  Tres propuestas.
[10:29.000 --> 10:33.000]  Ustedes analizan la parte técnica de las tres propuestas,
[10:33.000 --> 10:35.000]  y les envían tres propuestas.
[10:35.000 --> 10:36.000]  Tres propuestas.
[10:36.000 --> 10:41.000]  Ustedes analizan la parte técnica de las tres propuestas,
[10:41.000 --> 10:47.000]  y Raúl con su equipo también analizan la parte técnica de las tres propuestas.
[10:47.000 --> 10:50.000]  Los dos se juntan y toman una decisión.
[10:50.000 --> 10:55.000]  Y luego, transportadora Callao, que supongo es también Raúl,
[10:55.000 --> 10:57.000]  define por costos quíneces que convienen.
[10:57.000 --> 10:58.000]  Gracias.
[10:58.000 --> 10:59.000]  ¿Así es?
[10:59.000 --> 11:04.000]  Para montos mayores, porque está establecido unos montos para aprobaciones de servicios.
[11:04.000 --> 11:06.000]  Hay montos que son menores a 5.000,
[11:06.000 --> 11:11.000]  que directamente a decisiones puedes determinar cuál es la mejor oferta que va a recibir.
[11:11.000 --> 11:12.000]  ¿Quién decide eso?
[11:12.000 --> 11:13.000]  Directamente ¿qué?
[11:13.000 --> 11:14.000]  A decisiones, bajo contrato.
[11:14.000 --> 11:15.000]  A decisiones de Tramarsa.
[11:15.000 --> 11:16.000]  A decisiones de Tramarsa.
[11:17.000 --> 11:18.000]  ¿5.000 dólares?
[11:18.000 --> 11:19.000]  Sí, 5.000 dólares.
[11:19.000 --> 11:20.000]  ¿5.000?
[11:20.000 --> 11:21.000]  Sí.
[11:21.000 --> 11:22.000]  Está establecido...
[11:22.000 --> 11:23.000]  Sí, sí, sí.
[11:23.000 --> 11:24.000]  Los montos, ¿no?
[11:24.000 --> 11:25.000]  Encima de eso...
[11:25.000 --> 11:28.000]  Ahí tiene que aprobar transportadora Callao.
[11:28.000 --> 11:29.000]  ¿Quién? Raúl.
[11:29.000 --> 11:30.000]  Sí, Raúl.
[11:31.000 --> 11:34.000]  En este caso, para mantenimiento de esos robles vienen todas las aprobaciones.
[11:36.000 --> 11:38.000]  Antes de que llegue a...
[11:38.000 --> 11:45.000]  O sea, yo entiendo que en algún momento sus TDRs entran y se registran en el SAP de transportadora Callao.
[11:45.000 --> 11:52.000]  Sí, en el tema del registro de TDRs, a nivel Tramarsa, se realiza bajo un Excel.
[11:53.000 --> 11:56.000]  El documento, ya cuando se le envía a transportadora Callao,
[11:56.000 --> 12:00.000]  ellos escanean el documento, generan la SolPet,
[12:00.000 --> 12:07.000]  y con las aprobaciones que se tengan que realizar, generan la orden de compra.
[12:09.000 --> 12:15.000]  Finalmente, a decisiones se le envía recepciones y se empieza a invitar a los proveedores.
[12:15.000 --> 12:16.000]  OK.
[12:16.000 --> 12:20.000]  La propiedad es que enganche a decisiones Tramarsa para convocar proveedores por ruta.
[12:20.000 --> 12:27.000]  El sistema que usa Tramarsa, ¿es el sistema de transportadora Callao, el SAP?
[12:27.000 --> 12:28.000]  Sí.
[12:28.000 --> 12:32.000]  El software de mantenimiento es de transportadora, igual que el SAP.
[12:32.000 --> 12:37.000]  No, pero ¿el SAP es el que usa transportadora Callao?
[12:37.000 --> 12:38.000]  Sí.
[12:38.000 --> 12:41.000]  Ya, ese SAP es una SAP básica, ¿no?
[12:41.000 --> 12:42.000]  Una SAP para pymes, ¿verdad?
[12:42.000 --> 12:44.000]  Sí, es Business One, eso es básico.
[12:44.000 --> 12:45.000]  Es Business One.
[12:45.000 --> 12:47.000]  No tiene mantenimiento, es Business One.
[12:47.000 --> 12:48.000]  No.
[12:48.000 --> 12:49.000]  ¿No tiene?
[12:49.000 --> 12:50.000]  No.
[12:50.000 --> 12:56.000]  El desarrollador de Business One, la primera vez que se pidió,
[12:56.000 --> 13:01.000]  dijo que no podía desarrollar el módulo de mantenimiento como SAP R3.
[13:01.000 --> 13:02.000]  El PM.
[13:02.000 --> 13:07.000]  El SAP PM si hay, pero no es Business One.
[13:07.000 --> 13:12.000]  La razón por la cual tiene este software es que no tiene mantenimiento.
[13:13.000 --> 13:15.000]  No es Business One.
[13:15.000 --> 13:18.000]  La razón por la cual tiene este software que están usando.
[13:18.000 --> 13:22.000]  Por eso hicimos un software a la media.
[13:22.000 --> 13:25.000]  ¿Y ustedes si tienen acceso a los dos sistemas?
[13:25.000 --> 13:28.000]  O sea, ¿ingresan datos, interactúan con los dos sistemas?
[13:28.000 --> 13:31.000]  No, no tenemos acceso como mantenimiento.
[13:31.000 --> 13:35.000]  ¿A dónde no tienen el SAP de Business One, de Compress?
[13:35.000 --> 13:36.000]  Como mantenimiento no tenemos.
[13:36.000 --> 13:38.000]  ¿Eso lo maneja quién?
[13:38.000 --> 13:41.000]  Las áreas que lo manejan es todo transportador de AIO,
[13:41.000 --> 13:43.000]  todos los áreas de transportador de AIO,
[13:43.000 --> 13:46.000]  la área de adquisiciones de Tramarsa.
[13:46.000 --> 13:50.000]  Todas las demás áreas de Tramarsa no tienen acceso a esa información.
[13:50.000 --> 13:51.000]  Bien.
[13:58.000 --> 14:00.000]  En el contrato,
[14:00.000 --> 14:04.000]  ahorita solamente para comentar, aquí está la lista de herramientas.
[14:04.000 --> 14:07.000]  Entonces, esto es uno que está a cargo de Tramarsa,
[14:07.000 --> 14:09.000]  el equipamiento y las herramientas.
[14:09.000 --> 14:12.000]  Lo que nos comentabas era que si había un trabajo corto
[14:12.000 --> 14:16.000]  que se puede hacer con estas herramientas.
[14:16.000 --> 14:17.000]  ¿Todo eso tienen?
[14:17.000 --> 14:18.000]  Sí.
[14:18.000 --> 14:21.000]  ¿Quién definió todo eso?
[14:23.000 --> 14:25.000]  En las experiencias de su momento.
[14:25.000 --> 14:28.000]  Nos hemos visto data de 2019,
[14:28.000 --> 14:30.000]  cada actualización del contrato.

In [5]:
srt_file_1 = '/content/20241128_163155-Michael-Serva.srt'
srt_file_2 = '/content/20241128_160952-Michael-Serva.srt'
output_file = 'combined_transcript.srt'

with open(srt_file_1, 'r') as f1:
    content1 = f1.read()

with open(srt_file_2, 'r') as f2:
    content2 = f2.read()

with open(output_file, 'w') as outfile:
    outfile.write(content1)
    outfile.write('\n\n') # Add a separator between the two transcripts, if needed
    outfile.write(content2)

print(f"Combined SRT file saved to {output_file}")

Combined SRT file saved to combined_transcript.srt

In [3]:
import pandas as pd, os, re, numpy as np

# Load and parse the SRT
path="/content/combined_transcript.srt"
with open(path,'r',encoding='utf-8',errors='replace') as f:
    raw_lines=f.read().splitlines()

ts_re=re.compile(r'^\d{2}:\d{2}:\d{2},\d{3}\s+-->\s+\d{2}:\d{2}:\d{2},\d{3}')
num_re=re.compile(r'^\d+$')

utterances=[]
for line in raw_lines:
    if line=="":
        continue
    if num_re.match(line.strip()):
        continue
    if ts_re.match(line.strip()):
        continue
    utterances.append(line)

# Heuristic role classification (E1/E2/I1)
punct_re=re.compile(r'[^\wáéíóúüñÁÉÍÓÚÜÑ]+', re.UNICODE)
def tokenize(u): return [t for t in re.split(r'\s+', u.strip()) if t]
def norm_word(w):
    w=w.lower()
    w=punct_re.sub('', w)
    return w

ack_tokens=set([
    "ajá","aja","claro","ya","ok","okay","okei","sí","si","correcto","exacto","perfecto","bien","listo",
    "deacuerdo","de","acuerdo","mmm","mm","mhm","vale","dale","asi","así","seguro","totalmente","entendido","okey"
])
def ack_only(u):
    toks=[norm_word(t) for t in tokenize(u)]
    toks=[t for t in toks if t]
    if not toks: return False
    if toks==["bueno"]: return True
    return all(t in ack_tokens for t in toks)

def is_question(u): return ("?" in u) or ("¿" in u)
digit_re=re.compile(r'\d')
money_re=re.compile(r'(\$|s/|soles|dólar|dolar|usd|euros?)', re.I)
unit_re=re.compile(r'(tonelad|mill[oó]n|m3|kg|kwh|horas?|d[ií]as?|semanas?|meses?|años?|%|por\s+tonelada)', re.I)
def has_numbers(u): return bool(digit_re.search(u)) or bool(money_re.search(u))
def is_long(u): return len(tokenize(u))>=10 or len(u)>=70
def interviewer_cue(u):
    lu=u.strip().lower()
    return lu.startswith(("entonces","ya","ok","okay","a ver","veamos","podemos","pasemos","revisemos","quisiera","mira","perfecto"))

connectors=re.compile(r'^(que|porque|por que|y|adem[aá]s|incluso|luego|pero|bueno|o sea|más bien|también)\b', re.I)

def tag_question_informant(u):
    lu=u.strip().lower()
    if lu.startswith("¿"):
        return False
    return lu.endswith(("¿no?","¿cierto?","¿verdad?")) and (has_numbers(u) or unit_re.search(u))

# First pass: I1 vs interviewer
roles=[]
prev_is_question=False
prev_speaker=None
for u in utterances:
    q=is_question(u)
    ack=ack_only(u)
    nums=has_numbers(u)
    long=is_long(u)
    cue=interviewer_cue(u)
    wc=len(tokenize(u))
    if ack:
        typ="I1" if (prev_is_question and prev_speaker=="INT") else "INT"
    else:
        if q and not tag_question_informant(u):
            typ="INT"
        else:
            if prev_is_question and prev_speaker=="INT":
                typ="I1"
            elif prev_speaker=="I1" and connectors.match(u.strip()) and wc<=12 and not q:
                typ="I1"
            elif long or nums or unit_re.search(u):
                typ="I1"
            elif cue and wc<=12:
                typ="INT"
            else:
                typ="I1"
    roles.append(typ)
    prev_is_question = (q and not tag_question_informant(u))
    prev_speaker = typ

# Second pass: interviewer -> E1/E2 (E2 mostly backchannels / very short clarifiers)
final_roles=[]
for idx,(u,typ) in enumerate(zip(utterances,roles)):
    if typ=="I1":
        final_roles.append("I1")
    else:
        wc=len(tokenize(u))
        q=is_question(u)
        ack=ack_only(u)
        norm=" ".join([norm_word(t) for t in tokenize(u) if norm_word(t)])
        if ack or wc<=2:
            final_roles.append("E2")
        elif (not q) and wc<=4 and norm in {"ya","ok","okay","claro","perfecto","bien","listo","dale","correcto","exacto"}:
            final_roles.append("E2")
        elif q and wc<=4 and idx>0 and final_roles[idx-1]=="I1":
            final_roles.append("E2")
        else:
            final_roles.append("E1")

# Build TSV
n=len(utterances)
width=max(3, len(str(n)))
line_ids=[f"L{str(i+1).zfill(width)}" for i in range(n)]
df=pd.DataFrame({"LÍNEA_ID": line_ids, "ROL": final_roles, "TEXTO": utterances})

out_path="/content/roles_clasificados.tsv"
df.to_csv(out_path, sep="\t", index=False, encoding="utf-8")

df.head(25), out_path, n

(   LÍNEA_ID ROL                                              TEXTO
 0     L0001  I1            La 3 millones y pico de toneladas, ¿no?
 1     L0002  I1          Este año es 2.8 el objetivo de toneladas.
 2     L0003  E2                                    ¿2.8 toneladas?
 3     L0004  I1  Si, el año pasado si fue 3 millones, este año ...
 4     L0005  E1     Entonces tienes 1.8 entre... ¿cuánto me dices?
 5     L0006  I1                         2.8 millones de toneladas.
 6     L0007  I1                    Sale 0.64 dólares por tonelada.
 7     L0008  I1           El año anterior estaba en 0.4 hasta 0.6.
 8     L0009  E1                    A más volumen menos costo, ¿no?
 9     L0010  I1                     1.8 millones de mantenimiento.
 10    L0011  E1                ¿El presupuesto no lo puedes pasar?
 11    L0012  I1                                         Si, claro.
 12    L0013  E1  ¿Y vas a cumplir con todo lo planeado en el pr...
 13    L0014  I1                                         Si, hay...
 14    L0015  I1                              Según lo planeado si.
 15    L0016  I1  Incluso nos estamos perdiendo un poco de presu...
 16    L0017  I1             Que salieron por monitores de consumo.
 17    L0018  I1  Bueno, por trabajo correctivo programado que a...
 18    L0019  E1  ¿Y para el próximo año cuánto están... ya pres...
 19    L0020  I1                                      1.9 millones.
 20    L0021  E2                                   ¿El próximo año?
 21    L0022  I1                                                Si.
 22    L0023  E1  ¿Con cuánto de embarque van a tener? ¿Cuántos ...
 23    L0024  I1                             2.9 si no me equivoco.
 24    L0025  E1                ¿Millones de toneladas de embarque?,
 '/content/roles_clasificados.tsv',
 1552)

In [6]:
import pandas as pd, os, re, numpy as np

# Load and parse the SRT
# We will use the combined transcript file created previously.
path="/content/combined_transcript.srt"
with open(path,'r',encoding='utf-8',errors='replace') as f:
    raw_lines=f.read().splitlines()

ts_re=re.compile(r'^\d{2}:\d{2}:\d{2},\d{3}\s+-->\s+\d{2}:\d{2}:\d{2},\d{3}')
num_re=re.compile(r'^\d+$')

utterances=[]
# The original code here was trying to read from '/mnt/data/transcripcion_lineas.txt'
# which caused the FileNotFoundError. I've removed that section as 'raw_lines' is already populated.
# We just need to process these raw_lines into utterances.

# Nos quedamos con todas las líneas no vacías como utterances
# utterances = [line for line in raw_lines if line.strip() != ""]

for line in raw_lines:
    if line=="":
        continue
    if num_re.match(line.strip()):
        continue
    if ts_re.match(line.strip()):
        continue
    utterances.append(line)

# ==== 2. Heurística de clasificación de roles (E1/E2/I1) ====

punct_re = re.compile(r'[^\wáéíóúüñÁÉÍÓÚÜÑ]+', re.UNICODE)

def tokenize(u):
    return [t for t in re.split(r'\s+', u.strip()) if t]

def norm_word(w):
    w = w.lower()
    w = punct_re.sub('', w)
    return w

ack_tokens = set([
    "ajá","aja","claro","ya","ok","okay","okei","sí","si","correcto","exacto",
    "perfecto","bien","listo","deacuerdo","de","acuerdo","mmm","mm","mhm",
    "vale","dale","asi","así","seguro","totalmente","entendido","okey"
])

def ack_only(u):
    toks = [norm_word(t) for t in tokenize(u)]
    toks = [t for t in toks if t]
    if not toks:
        return False
    if toks == ["bueno"]:
        return True
    return all(t in ack_tokens for t in toks)

def is_question(u):
    return ("?" in u) or ("¿" in u)

digit_re = re.compile(r'\d')
money_re = re.compile(r'(\$|s/|soles|dólar|dolar|usd|euros?)', re.I)
unit_re = re.compile(r'(tonelad|mill[oó]n|m3|kg|kwh|horas?|d[ií]as?|semanas?|meses?|años?|%|por\s+tonelada)', re.I)

def has_numbers(u):
    return bool(digit_re.search(u)) or bool(money_re.search(u))

def is_long(u):
    return len(tokenize(u)) >= 10 or len(u) >= 70

def interviewer_cue(u):
    lu = u.strip().lower()
    return lu.startswith((
        "entonces","ya","ok","okay","a ver","veamos","podemos","pasemos",
        "revisemos","quisiera","mira","perfecto"
    ))

connectors = re.compile(r'^(que|porque|por que|y|adem[aá]s|incluso|luego|pero|bueno|o sea|más bien|también)\b', re.I)

def tag_question_informant(u):
    lu = u.strip().lower()
    if lu.startswith("¿"):
        return False
    return lu.endswith(("¿no?","¿cierto?","¿verdad?")) and (has_numbers(u) or unit_re.search(u))

# ==== 3. Primera pasada: INT (entrevistador) vs I1 (informante) ====

roles = []
prev_is_question = False
prev_speaker = None

for u in utterances:
    q = is_question(u)
    ack = ack_only(u)
    nums = has_numbers(u)
    long = is_long(u)
    cue = interviewer_cue(u)
    wc = len(tokenize(u))

    if ack:
        # backchannel / respuesta corta
        typ = "I1" if (prev_is_question and prev_speaker == "INT") else "INT"
    else:
        if q and not tag_question_informant(u):
            typ = "INT"
        else:
            if prev_is_question and prev_speaker == "INT":
                typ = "I1"
            elif prev_speaker == "I1" and connectors.match(u.strip()) and wc <= 12 and not q:
                typ = "I1"
            elif long or nums or unit_re.search(u):
                typ = "I1"
            elif cue and wc <= 12:
                typ = "INT"
            else:
                typ = "I1"

    roles.append(typ)
    prev_is_question = (q and not tag_question_informant(u))
    prev_speaker = typ

# ==== 4. Segunda pasada: separar entrevistadores en E1 / E2 ====

final_roles = []
for idx, (u, typ) in enumerate(zip(utterances, roles)):
    if typ == "I1":
        final_roles.append("I1")
    else:
        wc = len(tokenize(u))
        q = is_question(u)
        ack = ack_only(u)
        norm = " ".join([norm_word(t) for t in tokenize(u) if norm_word(t)])

        if ack or wc <= 2:
            final_roles.append("E2")
        elif (not q) and wc <= 4 and norm in {
            "ya","ok","okay","claro","perfecto","bien","listo",
            "dale","correcto","exacto"
        }:
            final_roles.append("E2")
        elif q and wc <= 4 and idx > 0 and final_roles[idx-1] == "I1":
            final_roles.append("E2")
        else:
            final_roles.append("E1")

# ==== 5. Construir TSV (3 columnas: LÍNEA_ID, ROL, TEXTO) ====

n = len(utterances)
width = max(3, len(str(n)))
line_ids = [f"L{str(i+1).zfill(width)}" for i in range(n)]

df = pd.DataFrame({
    "LÍNEA_ID": line_ids,
    "ROL": final_roles,
    "TEXTO": utterances
})

out_path = "/content/roles_clasificados.tsv"
df.to_csv(out_path, sep="\t", index=False, encoding="utf-8")

print("TSV generado en:", out_path)
print(df.head(10))

TSV generado en: /content/roles_clasificados.tsv
  LÍNEA_ID ROL                                                     TEXTO
0    L0001  I1                   La 3 millones y pico de toneladas, ¿no?
1    L0002  I1                 Este año es 2.8 el objetivo de toneladas.
2    L0003  E2                                           ¿2.8 toneladas?
3    L0004  I1  Si, el año pasado si fue 3 millones, este año ha bajado.
4    L0005  E1            Entonces tienes 1.8 entre... ¿cuánto me dices?
5    L0006  I1                                2.8 millones de toneladas.
6    L0007  I1                           Sale 0.64 dólares por tonelada.
7    L0008  I1                  El año anterior estaba en 0.4 hasta 0.6.
8    L0009  E1                           A más volumen menos costo, ¿no?
9    L0010  I1                            1.8 millones de mantenimiento.

In [8]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df)

,LÍNEA_ID,ROL,TEXTO
0,L0001,I1,"La 3 millones y pico de toneladas, ¿no?"
1,L0002,I1,Este año es 2.8 el objetivo de toneladas.
2,L0003,E2,¿2.8 toneladas?
3,L0004,I1,"Si, el año pasado si fue 3 millones, este año ha bajado."
4,L0005,E1,Entonces tienes 1.8 entre... ¿cuánto me dices?
5,L0006,I1,2.8 millones de toneladas.
6,L0007,I1,Sale 0.64 dólares por tonelada.
7,L0008,I1,El año anterior estaba en 0.4 hasta 0.6.
8,L0009,E1,"A más volumen menos costo, ¿no?"
9,L0010,I1,1.8 millones de mantenimiento.
10,L0011,E1,¿El presupuesto no lo puedes pasar?
11,L0012,I1,"Si, claro."
12,L0013,E1,¿Y vas a cumplir con todo lo planeado en el presupuesto?
13,L0014,I1,"Si, hay..."
14,L0015,I1,Según lo planeado si.
15,L0016,I1,Incluso nos estamos perdiendo un poco de presupuesto por actividades que no estaban planificadas.
16,L0017,I1,Que salieron por monitores de consumo.
17,L0018,I1,"Bueno, por trabajo correctivo programado que aparecieron."
18,L0019,E1,¿Y para el próximo año cuánto están... ya presentaron el presupuesto?
19,L0020,I1,1.9 millones.
20,L0021,E2,¿El próximo año?
21,L0022,I1,Si.
22,L0023,E1,¿Con cuánto de embarque van a tener? ¿Cuántos toneladas?
23,L0024,I1,2.9 si no me equivoco.
24,L0025,E1,¿Millones de toneladas de embarque?
25,L0026,I1,Si.
26,L0027,E2,¿2.9 o 1.9?
27,L0028,I1,Si.
28,L0029,I1,Lo que vendido salió.
29,L0030,I1,"1.9 entre 1.9, ¿no?"
30,L0031,I1,"Estoy mal, es 1.52 dólares por tonelada, ¿no?"
31,L0032,E1,Entonces el otro es...
32,L0033,E1,"Así es, ¿no? 1.52 dólares por tonelada."
33,L0034,I1,Claro.
34,L0035,I1,Más o menos.
35,L0036,I1,El presupuesto sobre el presupuesto de embarque.
36,L0037,E1,En los próximos 5 años ¿tienes un plan de capex?
37,L0038,I1,Plan de inversiones.
38,L0039,I1,"Si, para el reemplazo del mayor equipo, overhaul, etc."
39,L0040,I1,Se tiene hasta el 2030.
40,L0041,I1,Eso también necesitamos mirarlo.
41,L0042,E2,Si.
42,L0043,E1,¿Qué es lo que tienen pronosticado?
43,L0044,E1,"La faja creo que todavía está nueva, ¿no?"
44,L0045,I1,Se va a cambiar en el 2027.
45,L0046,E2,¿El 27?
46,L0047,E1,"Es la de mayor logito, ¿no?"
47,L0048,E1,¿Cuántas vidas tiene esa faja tubular?
48,L0049,I1,Cinco años.
49,L0050,E2,¿Tan poquito?
50,L0051,I1,Y está afectada en siete años.
51,L0052,I1,"La primera faja que cambiamos, cinco años."
52,L0053,E1,¿Cuántas vidas tiene esa faja tubular?
53,L0054,I1,Cinco años.
54,L0055,E2,¿Tan poquito?
55,L0056,I1,Y está afectada en siete años.
56,L0057,I1,"La primera faja que cambiamos, cinco años."
57,L0058,I1,"La segunda que está actualmente funcionando, siete años."
58,L0059,I1,Se afecta a siete años.
59,L0060,I1,Por eso el 2027.
60,L0061,I1,Los últimos cambios se terminan en 2020.
61,L0062,I1,Eso también es importante.
62,L0063,E1,"O sea, en este momento la faja más grande es la tubular, ¿no?"
63,L0064,E1,¿Y puede llevar hasta qué tonelaje? ¿2000?
64,L0065,I1,2200 toneladas por hora.
65,L0066,I1,2200 toneladas por hora.
66,L0067,E1,¿Y el promedio que están usando?
67,L0068,E2,¿1600?
68,L0069,I1,"No, 2000."
69,L0070,I1,El promedio es 2000.
70,L0071,I1,El mínimo es 2650.
71,L0072,E1,¿2000 toneladas es lo que están pasando en promedio?
72,L0073,I1,"Sí, promedio."
73,L0074,E1,¿Eso es lo que pasa en promedio al año?
74,L0075,I1,Pero no es en rate.
75,L0076,I1,"No es promedio en el periodo que descargan, sino en el promedio anual."
76,L0077,I1,Estamos hablando del reto de total de...
77,L0078,E1,"El promedio para tener una idea del desgaste, ¿no?"
78,L0079,I1,2000.
79,L0080,I1,"Porque la faja está para 2200 toneladas hora permanente, ¿no?"
80,L0081,I1,"Sí, 2000 toneladas está el promedio."
81,L0082,E2,¿2000 toneladas promedio anual?
82,L0083,I1,"Anual, exactamente."
83,L0084,I1,Eso es un control de productividad por parte de operaciones.
84,L0085,E2,"Ya, pero..."
85,L0086,I1,"Lo mínimo que pueden hacer es 1600, ¿no?"
86,L0087,I1,"Sí, por contrato."
87,L0088,I1,Y tú podrías hacer una nota de cuánto gastas...
88,L0089,E1,"Los últimos cinco años, ¿cuánto sirve el promedio?"
89,L0090,I1,El costo...
90,L0091,E1,"No, el promedio del aje pasado, ¿no?"
91,L0092,I1,"Bueno, se puede hacer entre los dos millones o el millón, ¿no?"
92,L0093,E2,Sí.
93,L0094,E1,"O sea, ¿cuántos tienes que hacer? ¿Cuántos tienes que pasar? ¿Dos millones? ¿Cuántos hay?"
94,L0095,I1,"2.8 millones. Este año, años anteriores, está en 3 millones."
95,L0096,I1,Esa faja estaría... El diseño de la faja...
96,L0097,I1,Hay que ver si...
97,L0098,E1,"En realidad esa faja está sobrada para lo que están haciendo, ¿no?"
98,L0099,I1,Porque trabajan períodos cortos nada más.
99,L0100,I1,No están pasando ni siquiera los 3 millones y pico que necesitan.
100,L0101,E1,"Entonces no debería ser cinco añitos, sino mucho más, ¿no?"
101,L0102,I1,"Sí, está, si no me equivoco, por fábrica indicaron que 10 años, ¿no?"
102,L0103,I1,"Trabajando al régimen a 24 horas, ¿no?"
103,L0104,E2,Sí.
104,L0105,E1,¿Y eso no ocurre?
105,L0106,I1,No. En operación...
106,L0107,E1,¿Y el espesor lo van chequeando?
107,L0108,I1,"Sí, le hacemos monitoreo de ultrasonido, fijándose en el tema del desgaste."
108,L0109,E1,¿Y cómo va el desgaste? ¿Ya han hecho su curvita?
109,L0110,I1,"Sí, tenemos una tendencia de desgaste."
110,L0111,I1,Estamos cambiando los primeros tramos de la faja que se han cambiado en 2019.
111,L0112,I1,"Todo el resto de la faja que se tiene está en seguimiento,"
112,L0113,I1,actualmente de daños en embalmes y cantos.
113,L0114,I1,En el desgaste no hay autoridad o criticidad de la zona de retorno.
114,L0115,I1,"Pero sí, se está evaluando el cambio de los espesores en la faja cantora."
115,L0116,E1,"La faja tubular es la parte más importante, aparte del chill loader, ¿no?"
116,L0117,I1,Sí.
117,L0118,E1,"Es lo más importante, ¿no?"
118,L0119,I1,Sí.
119,L0120,I1,Y lo más caro también.
120,L0121,E1,¿Cuándo han cambiado la faja?
121,L0122,I1,En 2019.
122,L0123,E2,¿Toda la faja?
123,L0124,I1,"Sí, toda la faja."
124,L0125,E1,"¿Rabu no estaba acá, no?"
125,L0126,I1,"No, no está."
126,L0127,E2,¿Quién lo hizo?
127,L0128,I1,"Jinka Cereza, el otro superínquilista."
128,L0129,E1,¿Y qué es de Jinka Cereza?
129,L0130,I1,La consultoría está ahí.
130,L0131,E2,¿Dónde está él?
131,L0132,I1,Está en Ica.
132,L0133,E2,¿En Ica?
133,L0134,I1,"Sí, ahí vive él."
134,L0135,E2,¿Y qué hace?
135,L0136,I1,"Hace consultorías, una empresa que ha formado conocidos."
136,L0137,E2,¿Construyó de qué mantenimiento?
137,L0138,I1,"Sí, en planta."
138,L0139,E2,¿De planta?
139,L0140,I1,"Sí, tipos de planta."
140,L0141,E1,¿Él no es el que está recomendando José Redondo?
141,L0142,E1,¿Y en Cáceres?
142,L0143,I1,Creo que sí.
143,L0144,E2,¿Él estuvo en Brocán?
144,L0145,I1,"Sí, estuvo en Brocán."
145,L0146,E2,"Estuvo en Brocán, ¿no?"
146,L0147,I1,"Sí, sí."
147,L0148,E1,¿Y después también creo que en Chinaco?
148,L0149,I1,"En Chinaco no, en Cerro Verde."
149,L0150,I1,Estuvo antes en Cerro Verde.
150,L0151,E2,¿Vino acá?
151,L0152,I1,"No, vino a Brocán y luego acá, o primero acá y luego a Brocán."
152,L0153,I1,"Estuvo en Fochil también, en Minerares."
153,L0154,E2,"Ya, ya, ya."
154,L0155,I1,En Brocán también.
155,L0156,I1,"Sí, pues él es."
156,L0157,I1,Y él es el que ha...
157,L0158,I1,"Cuando viene con Eduardo Kuh, ya estaba Raúl."
158,L0159,I1,"Sí, por 2022."
159,L0160,E2,Sí.
160,L0161,E1,"Y en Cáceres salió antes, ¿no?"
161,L0162,I1,Él es el que salió.
162,L0163,I1,Y Raúl lo reemplazó.
163,L0164,E2,Sí.
164,L0165,E1,¿Pero él era el de transportador a Callao?
165,L0166,I1,"Sí, el de transportador."
166,L0167,I1,Eso se hizo en el año 2019.
167,L0168,E2,¿Quién reemplazó esa faja?
168,L0169,I1,Fue empresa.
169,L0170,I1,Tecnomina.
170,L0171,E2,¿Estabas acá?
171,L0172,I1,Sí.
172,L0173,E1,¿Y cuánto tiempo duró esa faja?
173,L0174,I1,Cinco años.
174,L0175,E1,¿Y hubo desgaste suficiente para cambiarlo?
175,L0176,I1,"Sí, hubo desgaste."
176,L0177,I1,Este daño longitudinal de la faja.
177,L0178,I1,Con rotura.
178,L0179,I1,"Ah, se rompió."
179,L0180,I1,Con rotura.
180,L0181,E1,¿Y cuánto tiempo lo cambiaron?
181,L0182,I1,Se hizo progresivo.
182,L0183,I1,"Ah, se fue hecho en etapas."
183,L0184,I1,Por tragos.
184,L0185,I1,2019 tiene cinco años ahorita.
185,L0186,E2,Sí.
186,L0187,E1,¿Y cómo está la faja?
187,L0188,I1,Está en buenas condiciones.
188,L0189,I1,Hemos hecho injertos.
189,L0190,I1,Por eso se está estimando
190,L0191,I1,en el año 2020.
191,L0192,I1,Para darle una extensión de vida
192,L0193,I1,útil
193,L0194,I1,a la definición que se tiene.
194,L0195,I1,Hemos hecho algunas mejoras
195,L0196,I1,en esta última faja que se ha colocado.
196,L0197,I1,Incrementó el espesor en los cantos
197,L0198,I1,donde se veía más.
198,L0199,I1,Eso se hizo con Jim Cáceres.
199,L0200,I1,Incrementó el espesor.
200,L0201,E2,Ok.
201,L0202,I1,Hemos visto que teníamos desde el contrato
202,L0203,I1,una lista de actividades para conservación.
203,L0204,E1,¿Cómo se han ido mejorando?
204,L0205,E1,¿Cómo se procede mejor a esas actividades?
205,L0206,E1,¿Cómo se ve que de repente esto no es la frecuencia?
206,L0207,E1,¿O hay que hacer más cosas?
207,L0208,E1,¿O estas cosas ya no hay que hacerlas?
208,L0209,I1,Sí.
209,L0210,I1,En el contrato no se menciona mantenimiento correctivo.
210,L0211,I1,No he visto solamente correntido.
211,L0212,I1,Hay que mejorar lo que hacemos tanto
212,L0213,I1,a nivel de mantenimiento preventivo
213,L0214,I1,y el tiempo exacto
214,L0215,I1,para hacer el correctivo es
215,L0216,I1,en base a los monitores de condición
216,L0217,I1,que están realizándose
217,L0218,I1,tanto con la contrata que tenemos como SKF.
218,L0219,E2,¿Quién supervisa SKF?
219,L0220,I1,"Perdona, Tramarsa."
220,L0221,I1,Tramarsa.
221,L0222,E1,¿El contrato está bajo la supervisión de Tramarsa?
222,L0223,I1,Sí.
223,L0224,E1,Entonces eso es lo que hace
224,L0225,I1,con un punto de mejora.
225,L0226,E1,¿Y por qué no lo hacen ustedes?
226,L0227,I1,"O sea,"
227,L0228,E2,¿no tienen esas capacidades
228,L0229,E1,en esas competencias?
229,L0230,I1,Sí.
230,L0231,I1,Se propuso hacerlo con nosotros
231,L0232,I1,pero como un tema de
232,L0233,I1,enojado y experiencia
233,L0234,I1,en el mercado
234,L0235,I1,se tomó la decisión de hacerlo con
235,L0236,I1,"una empresa que ya reconocieron,"
236,L0237,I1,"SKF,"
237,L0238,I1,"SoulTrack,"
238,L0239,I1,que estuvieron dentro de la terna.
239,L0240,I1,Y quedaron con SKF.
240,L0241,I1,Y nos quedamos con SKF
241,L0242,I1,con otro contrato interesante.
242,L0243,E1,¿Ellos vienen permanente acá gente?
243,L0244,I1,Permanente.
244,L0245,I1,"Tres veces a la semana,"
245,L0246,I1,tres días a la semana.
246,L0247,E1,¿Vienen acá tres días a la semana?
247,L0248,I1,De ejecución en campo
248,L0249,I1,y dos días en ejecución de gabinete.
249,L0250,I1,"Dos en campo,"
250,L0251,I1,uno en gabinete.
251,L0252,E2,¿Y qué cosas
252,L0253,E2,les entregan?
253,L0254,I1,Les menciona cuál es
254,L0255,I1,la condición de cada equipo.
255,L0256,E2,¿Tienen puntos específicos
256,L0257,E2,que tomen?
257,L0258,I1,"Sí, tenemos una lista completa de todos los equipos que tienen intervenir"
258,L0259,I1,y los puntos de edición que tienen que tomar
259,L0260,I1,de cada equipo.
260,L0261,I1,"Iluminación radial, axial."
261,L0262,I1,"Iluminación, ultrasonido,"
262,L0263,I1,tecografía.
263,L0264,E1,¿Todo lo que es predictivo lo tienen ellos?
264,L0265,I1,"Sí, para la parte eléctrica."
265,L0266,I1,Y si hay algún requerimiento
266,L0267,I1,adicional que se tenga
267,L0268,I1,que realizar que no esté dentro del contrato
268,L0269,I1,punto
269,L0270,I1,hacia ese spot nada más
270,L0271,I1,y solicita también.
271,L0272,E1,"Ya, pero el contrato es"
272,L0273,E1,¿cuántas personas son?
273,L0274,I1,Tres. Tres personas.
274,L0275,E2,¿Y esa persona
275,L0276,I1,siempre ha enojado de todos
276,L0277,I1,"los contratos eléctricos, mecánicos"
277,L0278,E2,y todo eso?
278,L0279,I1,Nosotros trabajamos en conjunto toda la información
279,L0280,I1,que ellos requieran para poder
280,L0281,I1,crear un proyecto múltiplo en despacito.
281,L0282,I1,No.
282,L0283,E2,Ok.
283,L0284,E1,¿Es la única compañía permanente
284,L0285,E1,que está acá? ¿Es SCKF?
285,L0286,I1,No. Tenemos
286,L0287,E1,dos empresas más. ¿Quiénes son?
287,L0288,I1,"Que están viendo la infraestructura, que es"
288,L0289,I1,Parsa. Infraestructura.
289,L0290,I1,Infraestructura Parsa y
290,L0291,I1,Target One.
291,L0292,E2,¿Parsa y quiénes?
292,L0293,I1,Target. Target One.
293,L0294,I1,Target. De objetivos.
294,L0295,I1,De objetivos.
295,L0296,I1,Target One.
296,L0297,E2,¿Qué hace Parsa?
297,L0298,I1,Parsa hace renovaciones
298,L0299,E2,de
299,L0300,I1,estructuras metálicas
300,L0301,I1,"hablando de barandas,"
301,L0302,I1,"planchas,"
302,L0303,I1,"diferentes niveles,"
303,L0304,I1,escaleras.
304,L0305,E2,¿Eso es más
305,L0306,E2,soldadura?
306,L0307,I1,"Sí, soldadura"
307,L0308,I1,y pintado también.
308,L0309,E2,"¿También pintan? Sí, pintado."
309,L0310,E2,¿Para qué?
310,L0311,I1,Por la corrupción.
311,L0312,E2,¿Y Target One?
312,L0313,I1,Target One es la limpieza de zonas inaccesibles.
313,L0314,I1,Zonas inaccesibles.
314,L0315,E1,"Pero si no son inaccesibles, ¿cómo lo pueden limpiar?"
315,L0316,I1,De difícil
316,L0317,I1,acceso será.
317,L0318,E2,"Bueno,"
318,L0319,I1,de los que
319,L0320,I1,están en acturas superiores
320,L0321,I1,para colgarse.
321,L0322,I1,Para colgarse.
322,L0323,I1,Para pintar.
323,L0324,E2,¿Pintan también? Sí.
324,L0325,I1,"Lo que es la misma estructura,"
325,L0326,I1,"las coberturas, las galerías estas."
326,L0327,I1,Eso es lo que hacemos.
327,L0328,I1,Y hoy también estamos toda la semana.
328,L0329,E2,¿Pero son nuevos?
329,L0330,I1,Sí. Tienen
330,L0331,I1,más o menos seis meses.
331,L0332,E1,¿Quién tiene seis meses? Target One.
332,L0333,I1,"Seis meses, seis meses."
333,L0334,I1,El servicio se solicitó instantáneamente.
334,L0335,E2,¿Cómo?
335,L0336,I1,El servicio se pidió en el mismo momento.
336,L0337,I1,El servicio fue en el mes de marzo
337,L0338,I1,más o menos.
338,L0339,I1,Para ambos requerimientos.
339,L0340,E1,Vaya. ¿No había ese servicio?
340,L0341,I1,"No, no."
341,L0342,E2,"Era puntual, ¿no?"
342,L0343,I1,Sacábamos servicios.
343,L0344,I1,Esto ya es continuo. Eso es un contrato
344,L0345,I1,de un año. Un año. Ajá.
345,L0346,E2,¿Cuánta gente tiene Parza?
346,L0347,I1,Cinco. Cada uno.
347,L0348,I1,"Cinco, cada uno y..."
348,L0349,E2,Cada empresa. ¿Ah?
349,L0350,I1,Cada empresa tiene cinco.
350,L0351,I1,Cada empresa tiene cinco personas.
351,L0352,I1,"Ah, cinco personas. Pero tienen facilidades."
352,L0353,I1,"Tienen camionetas, materiales, todo lo que..."
353,L0354,I1,Los materiales lo probamos.
354,L0355,I1,Lo probé. Traportó a la calle.
355,L0356,I1,No fue requerimiento.
356,L0357,I1,La pintura...
357,L0358,I1,Todos los insumos para el mantenimiento
358,L0359,I1,lo probé. Traportó a la calle.
359,L0360,E1,"Entonces, ¿qué ponen esta gente?"
360,L0361,E1,¿Solamente manual de obra? Manual de obra.
361,L0362,I1,Y equipos menores que realmente tienen
362,L0363,I1,para el control de calidad de sus
363,L0364,I1,actividades.
364,L0365,I1,"Y los andaámeos, los..."
365,L0366,I1,Va con parte de sus servicios.
366,L0367,I1,"O sea, los insumos, sí,"
367,L0368,I1,vienen por la transportadora y
368,L0369,I1,el resto viene por ellos.
369,L0370,I1,Equipos especiales como Manleaf.
370,L0371,I1,Manleaf de ellos también.
371,L0372,I1,"Ah, transportadora."
372,L0373,E1,¿Y quién los supervisa? ¿Ustedes?
373,L0374,I1,"Sí. O sea, transportadora que allá"
374,L0375,I1,uno los contrata y usted el tramasa
375,L0376,I1,los supervisa. Sí.
376,L0377,E2,Ok.
377,L0378,E1,"Tríos, ¿de dónde?"
378,L0379,I1,Sobre la criticidad
379,L0380,E1,"de los equipos, ¿no? Que tienen una"
380,L0381,I1,forma de calcularlos en contra de los equipos.
381,L0382,I1,Eso se...
382,L0383,I1,Se está revisando en el tiempo
383,L0384,I1,para ver si un equipo
384,L0385,I1,por alguna razón se vuelve más crítico
385,L0386,I1,o ha cambiado
386,L0387,I1,de repente la forma de terminar
387,L0388,I1,cuando un equipo es crítico. Inicialmente
388,L0389,I1,nosotros como Tramarsas teníamos esa
389,L0390,I1,esa evaluación de análisis de criticidad
390,L0391,I1,del equipo.
391,L0392,I1,A la presenta que este año pasó
392,L0393,I1,en base a una auditoría que tuvimos de calidad
393,L0394,I1,los profesionales de la transportadora
394,L0395,I1,deberían manejar esa análisis de criticidad.
395,L0396,I1,"Pero sí, año a año"
396,L0397,I1,se va evaluando el tema
397,L0398,I1,de la criticidad en base a
398,L0399,I1,"factores como la operacionalidad,"
399,L0400,I1,"tiempo de falla de cada uno de los equipos,"
400,L0401,I1,"si afectaba o no la seguridad,"
401,L0402,I1,"si un tema de logística que se debe tener en stand-by,"
402,L0403,I1,se ha hecho una evaluación
403,L0404,I1,y actualmente ya
404,L0405,I1,la tienda es que bajo su
405,L0406,I1,estándar mantiene otra operacionalidad.
406,L0407,I1,Es parte
407,L0408,I1,de su contra incluso.
408,L0409,I1,Y a partir de ahí
409,L0410,E1,"entonces ellos, las mejores"
410,L0411,I1,o el cambio de los criterios
411,L0412,I1,está por responsabilidad de ellos.
412,L0413,I1,Ustedes lo reciben como insumo.
413,L0414,I1,"Equipo crítico, equipo crítico."
414,L0415,E1,¿Y qué niveles de criticidad hay?
415,L0416,I1,Tenemos la faja.
416,L0417,I1,"O no, digo, los niveles de criticidad."
417,L0418,I1,"Ah, estos son solo tres niveles."
418,L0419,I1,"Críticos, mediadamente críticos"
419,L0420,I1,y no críticos.
420,L0421,E2,OK.
421,L0422,E1,¿Y críticos que va a hacer?
422,L0423,I1,"No, mediadamente los equipos de la línea principal."
423,L0424,I1,"Fajas, estores."
424,L0425,E2,OK.
425,L0426,I1,El teléfono.
426,L0427,I1,En cuanto a
427,L0428,I1,el mantenimiento
428,L0429,I1,para equipos regulados
429,L0430,I1,equipos por ley
430,L0431,I1,tienen que tener un tratamiento especial.
431,L0432,E2,¿Tienen ustedes
432,L0433,E1,ese tipo de equipos?
433,L0434,E2,¿Tienen alguna
434,L0435,I1,"reglamentación especial, alguna norma"
435,L0436,I1,que te diga que tiene que ser un tipo específico
436,L0437,E1,"de mantenimiento, de control sobre el mundo de ellos?"
437,L0438,I1,Claro. Equipos como
438,L0439,I1,el sistema de trizón e incendios
439,L0440,I1,están bajo la norma y tenemos que tener
440,L0441,I1,certificaciones.
441,L0442,I1,Las pozas a tierra también están
442,L0443,I1,controladas base a la norma
443,L0444,I1,eléctrica con la ley
444,L0445,I1,de ecuadignación electricidad.
445,L0446,I1,El tema de
446,L0447,I1,las oleas.
447,L0448,I1,Tenemos a lo que requiere el fabricante
448,L0449,I1,para los que es calado de los rodamientos.
449,L0450,I1,Así como estos
450,L0451,I1,hay varios
451,L0452,I1,temas también de las reparaciones
452,L0453,I1,organizados de las fajas.
453,L0454,I1,Está establecido también su temperatura y presión
454,L0455,I1,con cual del
455,L0456,I1,de organización de la actividad
456,L0457,I1,para realizar la calidad del
457,L0458,I1,trabajo.
458,L0459,E1,¿Y eso de ahí tiene
459,L0460,E1,"registros? ¿Tiene evidencia, almacenada"
460,L0461,E2,e insistematica?
461,L0462,I1,"Sí, tenemos registro porque es controlado"
462,L0463,I1,también en las auditorías.
463,L0464,I1,Igual que la balanza
464,L0465,I1,tiene que estar calibrada y certificada
465,L0466,I1,sus pesas patrón
466,L0467,I1,que tenemos en nuestras fajas
467,L0468,I1,y todo lo más
468,L0469,I1,que mencionamos.
469,L0470,E1,¿Y allí quién es el responsable
470,L0471,E1,de generar la información?
471,L0472,I1,Nosotros
472,L0473,I1,es lo que establecemos
473,L0474,I1,todo lo que debe.
474,L0475,E1,Ya se estableció en realidad
475,L0476,I1,lo que es tener
476,L0477,I1,especificado un control
477,L0478,I1,de calidad peligrosa.
478,L0479,E2,¿Y quién se encarga?
479,L0480,E1,¿Quién tiene la base de datos
480,L0481,E1,o el repositorio?
481,L0482,I1,Se entrega.
482,L0483,I1,Nosotros lo decimos tanto como transportador
483,L0484,I1,lo que ha sido la información como trámase.
484,L0485,I1,Pero como flujo de
485,L0486,I1,aprobación y finalmente el pago
486,L0487,I1,que también va de la mano
487,L0488,I1,"lo validamos, lo enviamos"